### ISSUE TITLE
textProcessor error

### ISSUE THREAD

**Issue by ahalterman** [bstewart/stm#1]
I'm getting an error on the `textProcessor()` function when I try to use it on my full 4000 row df (6 MB as an .rda), but no error on a 100 row sample of it.

```
Error in UseMethod("meta", x) : 
  no applicable method for 'meta' applied to an object of class "try-error"
In addition: Warning messages:
1: In mclapply(content(x), FUN, ...) :
  scheduled core 1 encountered error in user code, all values of the job will be affected
```

Here's a 1000 line sample of the data I'm using: https://www.dropbox.com/s/60n86skjf9f3ybo/recap-sample.rda

I used both the CRAN and current GitHub versions of STM with the same error.

Code to replicate:

```
library(stm)
load("recap-sample.rda")

recap.processed <- textProcessor(documents=recapsample$Text, metadata=recapsample)
# error
recapsample <- recapsample[1:100,]
recap.processed <- textProcessor(documents=recapsample$Text, metadata=recapsample)
# no error
```

Any idea what's going on?

**Comment by RadhikaGandhi** [comment]
Thanks, the above piece of code helped with mclapply error.
