### ISSUE TITLE
Suggestion: set spectral initialization as default

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#106]
Hi Brandon,

this is really only a minor suggestion, but I think that you should set the spectral method as default intialization in the stm call. The reason is simple: You pretty much recommend this in every document that I find and every talk that I see from you about STM. I guess the order at the moment, ``init.type = c("LDA", "Random", "Spectral")`` is alphabetic, but why not just change this?

**Comment by bstewart** [comment]
Good suggestion- honestly I just kept putting it off.  it used to not work when the vocab was large which made it a bad default.  I'll change it for the next round, its a good idea.

**Comment by methodds** [comment]
Cool, many thanks  :)

I'd take the freedom to highjack this thread for a completely different question and if you don't have time to  answer it, please don't worry about it:

I'm just going through the material for the CSS summer institute and found Christopher Bails network approach for text similarities. At one point he discussed that a problematic part is to determine where to set the cutoff for whether an edge is formed. I noticed that this problem is very similar to the stm topic correlation graph problem and figured that one might as well use the `huge` package for that. I tried and it a) worked + b) the results made sense to me.

Other than the fact that there is probably no "best" solution to this problem, do you think this approach is reasonable? Or do you see any methodological or other issues?

**Comment by bstewart** [comment]
Seems reasonable to me!  I always liked the huge paper.  It has been a number of years since I read it so it might be worth taking a look and making sure there is no huge caveat there.  But selection in a Gaussian graphical model is one of those topics that I think the stats community is near constantly making progress on.
