### ISSUE TITLE
date variable as covariate

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#11]
Hi,

I'd like to use a date variable (Y-m-d) as a prevalance covariate in the model. While calculating the model works after converting to date format, trying to plot estimated effects (continuous) does not.
How can I prevent this form happening? I saw that you converted dates to a simple ``days`` variable in your vignette. Are there alternatives?

Cheers

**Comment by bstewart** [comment]
Yeah you are going to want to work with the numeric representation and then just convert your axes back.  The key is the model needs to know how you want to numerically represent the date.  There is an example on page 19 of the vignette that shows how to create a set of labels.  

Will that cover your use case?

**Comment by methodds** [comment]
Thanks for the fast response =) Yes, adapting your example worked well. I thought there might be an easier solution, but this is totally fine as well.
