### ISSUE TITLE
A unknown error has occured in Rtsne

### ISSUE THREAD

**Issue by santoroma** [bstewart/stm#110]
Hi Brandon!
I'm sorry but I still have a problem when  k=0 the same of the closed issue 71.
I updated to last version of the master branch.
These are the messages:
```
Reloading installed stm
stm v1.3.0 (2017-09-08) successfully loaded. See ?stm for help.
> stm(DFM, K = 0, init.type = 'Spectral')
Beginning Spectral Initialization 
	 Calculating the gram matrix...
	 Finding anchor words...
 	
Error in tsneAnchor(Q) : an unknown error has occured in Rtsne
```
Surely the problem is  DFM2: a Document-feature matrix of: 30 documents, 44 features (68.9% sparse).
If I use DFM: a Document-feature matrix of: 30 documents, 8268 features (68.9% sparse) it works!
DFM2 is  DFM2 <- DFM %>% dfm_trim(min_count = min_freq, max_count = max_freq) with min_freq <- 0.001 and max_freq <- 0.95
Empirically I see that for a  Document-feature matrix of 30 documents and more than 100 features, it works!

Clearly the problem is for few features in the DFM: can you explain why?
May be can you insert a control/warning message?

Thanks a lot,
Mario

**Comment by bstewart** [comment]
Mario,

So Sorry! Sad to see this is still an issue.  Any chance you could send me a small replicable example so I can figure out what is going on there.

Brandon

**Comment by santoroma** [comment]
Yes I will do it. 
Can I use the bms4 email address of Princeton University?
I'm sorry it's the first time...

Mario

**Comment by bstewart** [comment]
Yes.  Thanks!

**Comment by santoroma** [comment]
Ok, I sent you the email....

**Comment by bstewart** [comment]
Thanks for the amazing replication file.  I found the issue: here is the corresponding NEWS item:

> Fixing a bug in K=0 where the method could fail if the perplexity was too large. It now automatically tries to reset itself.  To help with this in the future the initial dimension and perplexity values can now be set through the control options in stm.  Thanks to Mario Santoro for the bug catch and excellent replication file.

There is more in the help file for stm about setting these parameters.  Once the build tests pass I'll merge this into the master branch and close this issue out.
