### ISSUE TITLE
[Searchk()] Not work with 1.3 version, But work with 1.2.2(old version)

### ISSUE THREAD

**Issue by iamkbpark** [bstewart/stm#112]
Dear Dr. Stewart and team:

First of all, I would like to express my sincere appreciation about this package along with STM theory.
I have been using stm for several months successfully.
However, with the newest version (1.3), I have trouble using `searchk()` showing the error msg like below:

> Error in matrix(as.integer(x), nrow(x), ncol(x)) : 
> # non-numeric matrix extent

I could not figure out why and tried using previous version (1.2.2) and it worked.
Could you advise what cause this issue?
Since I am very much delighted to use `searchk` with `cores` argument in 1.3 version, I would like to solve this issue for my existing and future research.

Thank you for your time and help in advance.

**Comment by bstewart** [comment]
Thanks for reporting this.  I've been able to reproduce and will figure out what's going on.  I appreciate you bringing it to my attention!

**Comment by iamkbpark** [comment]
I do appreciate your prompt response and hard working on this fantastic package! Look forward to hearing from you soon. - Sincerely, KB Park

**Comment by bstewart** [comment]
So I found and fixed a problem in the development branch that will produce this error, but not one that would explain why it stopped working in V1.3 (it was an issue that was intermittent in the sense that it might work under some randomizations but not others).  Could you test on your case?
you can install the development branch using
`devtools::install_github("bstewart/stm", ref="development")`

**Comment by bstewart** [comment]
Fix is now in the master branch.

**Comment by iamkbpark** [comment]
Dear Dr. Stewart: 

I tested and it worked with the fixed master version.
However, the resulting diagnostic values differ significantly for Held-Out Likelihood and Residuals
Those two values from 1.3 version are trending exact opposite for the ones from 1.2.
Could you advise what might cause this?

If you need my data object and codes, I will be more than happy to share with you.
Then, please let me know how I can send you my codes and data object.
Thank you for your time and help.

Sincerely,
KB Park

**Comment by iamkbpark** [comment]
Thank you for your help, Dr. Stewart.
It is working now but there was an issue with diagnostic results.
So, I opened new issue.
Thank you for your time.
