### ISSUE TITLE
toLDAvis functionality

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#12]
Hi,

I just discovered the little helper function ``toLDAvis`` and really like this possibility to quickly inspect the model. Is it also possible to feed another metric to LDAvis, say, FREX values?

And is there a easy solution to store topic proportions in a variable? I'd like to feed them into a graph for topic correlations.

**Comment by bstewart** [comment]
We didn't write LDAvis, its just a wrapper to convert into format that works for their system.  So I think that's something to look at on their side.

**Comment by bstewart** [comment]
On the second question

> And is there a easy solution to store topic proportions in a variable? I'd like to feed them into a graph for topic correlations.

The returned model object stmobj has a component stmobj$theta which for each row contains the document proportions.  There are also functions for creating graphics of topic correlations built in to the package if you like.

**Comment by methodds** [comment]
Alright I'll contact the ``LDAvis`` creators. For the graphs I already found  your function for creating graphs but prefer to have a little bit more freedom. Many thanks for the theta hint.
