### ISSUE TITLE
PrepDocuments deleted rows 

### ISSUE THREAD

**Issue by nhthienvuong** [bstewart/stm#122]
Hi Brandon, 

I just noticed this, but when documents and their corresponding rows are deleted by PrepDocuments, the row names in the data frame are not renumbered. 

![image](https://user-images.githubusercontent.com/27565801/32301269-a268f410-bf33-11e7-9872-a59bd5e0f132.png)

I just renumbered it with another variable to help with the joins.

**Comment by bstewart** [comment]
yeah the theory is that either you have a unique identifier or you have simply moved all the data through the metadata object together.  Rownames as a way to do joins makes me nervous.

I'm going to leave this here though to remind me to clarify what is going on here in the helpfile.
