### ISSUE TITLE
Wishlist: Scale topicCorr plot by topic size

### ISSUE THREAD

**Issue by bstewart** [bstewart/stm#125]
in the manner of ldaVis

**Comment by gharp** [comment]
For what it's worth, we've found a dendrogram to be a pretty useful map of topic correlations and structure. This one was made by taking the json sting from the topicCorr html output and adding some additional variables for the proportions, topic names, topic numbers, etc. I end up needing to hand-label and tweak the design in Illustrator for communication purposes once I export it as a svg from the D3 browser viz. 

[collapsible-tree-example.pdf](https://github.com/bstewart/stm/files/1454469/collapsible-tree-example.pdf)

**Comment by bstewart** [comment]
This is really nice!  Thanks for sharing!
