### ISSUE TITLE
Local estimation error

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#14]
Hi Brandon,

when trying to estimate effects on topic proportions locally I receive an error:

```
prep <- estimateEffect(c(1:86) ~ s(numdate), pegida_stm, metadata=posts, uncertainty='Local',
                      documents=out$documents)

Error in base::colSums(x, na.rm = na.rm, dims = dims, ...): 'x' must be an array of at least two dimensions
Traceback:
, uncertainty='Local',
                      documents=out$documents)
1. estimateEffect(c(1:86) ~ s(numdate), pegida_stm, metadata = posts, 
 .     uncertainty = "Local", documents = out$documents)
2. thetaPosterior(stmobj, nsims = 1, type = thetaty, uncertainty='Local',
                      documents=out$documents)pe, documents = documents)
3. thetapost.local(model, documents, nsims)
4. ln.hess(eta, theta, doc.beta, doc.ct, siginv)
5. colSums(EB)
6. colSums(EB)
7. base::colSums(x, na.rm = na.rm, dims = dims, ...)
8. stop("'x' must be an array of at least two dimensions")
```

Is it incorrect to use `out$documents` for the documents? Global estimation works without problems for me. Can you maybe give short explanation why one would prefer one over the other (local vs global)?

Thanks and Cheers,
Carsten

**Comment by bstewart** [comment]
Carsten,

Thank you so much for alerting me to this.  It seems a problem got introduced when we made the jump to C++.  I have found the problem and will fix it in the next release.  At this point, I'd honestly recommend using the global estimation anyway.  The local uncertainty is so expensive to compute and the coverage does not appear to be any better as best we can tell from simulation.

Brandon
