### ISSUE TITLE
Using TxtOrg and STM

### ISSUE THREAD

**Issue by eh1234** [bstewart/stm#142]
I have been using an older version of r/STM so that I can use the `type= "txtorgvocab"` feature in _readCorpus_. I recently updated to STM  v1.3.3 and am no longer able to use the Delimited .csv exports from TxtOrg (the only options are "dtm", "slam", or "Matrix".

As TxtOrg provides the best pre-processing features for my corpus of documents, I would prefer to use its outputs. Do you have any recommendations for how I can import my TxtOrg documents/vocabulary files into STM? Thanks so much!

**Comment by bstewart** [comment]
If I remember correctly txtorg outputs in LDA-C format so you can use `readLdac()`.  For the vocab, its just a csv file so you can read it in with `read.csv()` just double check a few values to make sure everything has lined up properly.  If you have trouble just post a sample file here and we can see what we can do.

**Comment by eh1234** [comment]
**Thank you so much**-- importing the vocab and documents files worked, but when I tried to estimate the model like I've been doing, I got this error message: 

> Vocab length does not match observed word indices

I will get a sample file ready and can upload it soon-- just doing a normal TxtOrg output and not setting any thresholds.

**Comment by eh1234** [comment]
Here are the TxtOrg Sample Exports:

Vocab
Documents
Metadata

Thank you so much for your help!

[Sample TxtOrg Outputs.zip](https://github.com/bstewart/stm/files/1749820/Sample.TxtOrg.Outputs.zip)

**Comment by bstewart** [comment]
Here you go.
```
documents <- readLdac("sampleexport.csv")
vocab <- readLines("sampleexport_vocab.csv", encoding="UTF-8",warn=FALSE)
meta <- read.csv("sampleexport_metadata.csv",stringsAsFactors = FALSE)
```

**Comment by eh1234** [comment]
Thank you so much for your help- really appreciate it.
