### ISSUE TITLE
searchK prevalence issue

### ISSUE THREAD

**Issue by rmblum** [bstewart/stm#144]
This issue is somewhat similar to one I saw in the closed issues (where the user's metadata contained missing observations), but my problem is flipped. When using searchK I keep receiving the following error:

`Error in stm(documents = heldout$documents, vocab = heldout$vocab, K = k,  : 
  number of observations in content covariate (58910) prevalence covariate (58750) and documents (58910) are not all equal.`

When I check, all covariates have the same (58910) number of observations. I cannot find an instance where any of my prevalence covariates have more than 58910 observations, despite searchK returning this error. I'm happy to share my data, etc! I just would love to resolve this issue so I can explore my data further.

**Comment by bstewart** [comment]
Sure- why don't you email me with a dropbox link and I'll take a look.  Based on the way that error is calculated it isn't clear to me how this would happen without the prevalence covariates having fewer observations but it will be easier to see in a particular dataset.

**Comment by bstewart** [comment]
Also just to be 100% clear- you can't have missing data in the prevalence covariates either.  So if you have missing observations there that is likely your problem.

**Comment by rmblum** [comment]
Hi Brandon,

Thanks for helping with this. This dropbox folder contains the data and the
snippet of STM code I've been using. I do not believe there is any missing
data, though this is a large and unruly dataset so it's possible I missed
something. I'm definitely baffled as to why it's saying my prevalence cov
have *more *rather than fewer observations (I've tried it with multiple
prevalence cov's for the same result).

https://www.dropbox.com/sh/89n679516umtj1b/AAC9RFk1Cw4FRDS9pTHfleZXa?dl=0

**Comment by bstewart** [comment]
Yep- like I suggested.  Missing data:
![image](https://user-images.githubusercontent.com/577337/37291807-d78ee208-25e5-11e8-8a2d-a9856ec67d02.png)

The easiest way to deal with this is at the very beginning before doing any of the text processing.  You can also deal with it after the fact like this:
```
#find the missing values
keep <- !is.na(meta$PVI)
#keep only observed values in meta and docs
meta <- meta[keep,]
docs <- docs[keep]
#rerun prepDocuments to deal with missing vocab
out <- prepDocuments(docs, vocab, meta, lower.thresh=3)
docs <- out$documents
vocab <- out$vocab
meta <-out$meta
#now everything should be fine
mod <- stm(docs, vocab, K=50, init.type="Spectral", prevalence =~ PVI, data=meta)
```

**Comment by rmblum** [comment]
Thank you so much. That does, indeed, solve the problem.
