### ISSUE TITLE
Keep hashtags in textprocessing

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#15]
Is there a way to keep hashtags in the documents without having to rely on external textprocessors? I would like to remove punctuation and numbers but keep hashtags.

At the moment I'm using [quanteda](https://github.com/kbenoit/quanteda) preprocessing which enables just this, but the resulting matrix has to be converted back  to a stm friendly format afterwards.

**Comment by bstewart** [comment]
This can't be done as it currently stands but quanteda does have a way to convert to stm format.  I'll give some thought to whether this could be added as an option.

**Comment by methodds** [comment]
Hey Brandon, I already talked to the ```quanteda``` guys and all bugs for their convert function are now fixed, meaning I can easily use this. No need for you to do extra work :) Thanks anyway.

**Comment by bstewart** [comment]
Great!
