### ISSUE TITLE
Advice for using covariates with many levels?

### ISSUE THREAD

**Issue by mfherman** [bstewart/stm#159]
Firstly, thank you so much for the wonderful package. Not only has the software been incredibly useful for my work, the documentation and published papers are exceptional!

One issue I've been having is that when I include a categorical covariate with a large number of levels, the model runs incredibly slowly. In other cases, I might collapse the particular variable to a smaller number categories, but here the covariate I want to use is the author of the document. Essentially, I would like  to control for individual author in my STM model. In my corpus of around 30,000 documents, I have around 350 different authors.

Is there another approach you would suggest? Or does it even make sense to include an author as a covariate in STM?

Thanks again!

**Comment by bstewart** [comment]
Thanks for the kind words!

As a prevalence covariate?  If so set `gamma.prior="L1"` and it will pretty dramatically speed up.  This will use a sparsity inducing prior which will pool most authors together on most topics.  You can actually make it more comparable to the default setting (but still quite a bit faster) by also setting `control=list(gamma.enet=0)` which uses a ridge prior.  At this point its just different ways of setting how much regularizing as done.

**Comment by mfherman** [comment]
I was actually thinking that I should use the author as a content covariate, thinking that certain authors are more or less likely to use certain words when they write about the same topic. Does that make sense?

I also will try your suggestion for setting the gamma prior and using the author as a prevalence covariate.

**Comment by bstewart** [comment]
Unfortunately the content covariate problem is just hard- there is no faster fix here.  The optimization problem is incredibly difficult and the number of parameters is enormous (number of topics (K) times number of words (V) times number of authors (A)). 

One option would be to turn off interactions.  This shrinks the number of parameters from K*V*A to (K+A)*V which is a lot better.  It will be faster but not fast per se.

**Comment by mfherman** [comment]
Got it, and thanks for the helpful suggestions! I'll try to turn of interactions for the content covariate, but I think either way I'll probably run into memory issues on my local machine.

As I'm planning to use the results of the topic model for future prediction/classification of a non-text outcome, perhaps I'll be able to include the author as a feature in that predictive model.

Thanks again for all your work on STM!
