### ISSUE TITLE
searchK error for models with content covariates

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#17]
Hi,

**after** computing `searchK` for models with content covariates an error is raised:

```
Error in exclusivity(model, M = M, frexw = 0.7) : 
  Exclusivity calculation only designed for models without content covariates
```

I think a more elegant solution would be to either not calculate exclusivity for content models in `searchK`, or directly forbid to use`searchK`on them in the first place.

Cheers,
Carsten

**Comment by bstewart** [comment]
Yep.  I agree.  More efficient to write a loop over K.  Certainly an advantage of that is that if you have multiple machines you can run a different model on every machine.

**Comment by towashington** [comment]
I encountered the same error searching for models with content covariates. However, the error pops up when the initialization is "LDA" but doesn't when it is "Spectual" --- the default method. Why is that? If LDA is preferred for my research, how should I avoid the error? Thanks.
