### ISSUE TITLE
Systematic mistakes in topic-term assignment

### ISSUE THREAD

**Issue by emiliekuleuven** [bstewart/stm#178]
Hi, 

I have been using stm for 3 months now on a slightly different application. I have individual descriptions of the tasks that people perform from job descriptions. I am using stm without covariates to estimate the latent themes in job tasks. Looking at the beta vectors and the correlation between the topics has generated really interesting and intuitive responses. However, when I look at the gamma vectors for each individual (every individual is a document in my setting that describes their competencies), I find some very strange assignments that don't add up to the topic content. Even workers with the same job description that get assignment (radically) different topics. 

Let me give you an example that I hope will illustrate. (results are from estimating on subset of the data...)
tasks_dfm is a cast_dfm from tidy document_term data.

```
stmtopic20 <- stm(tasks_dfm, K = 20, init.type = "Spectral")
plot.STM(stmtopic20, type = "summary", n = 5)
```

![afbeelding](https://user-images.githubusercontent.com/9107730/49294358-067d5300-f4b3-11e8-9d0c-9f41759aa0c6.png)

The model converges  very quickly without issues.
In the picture you can see some very intuitive results: most common topic 16 is about clerical work, topic10 is about product/assebly lines workers etc. , but them when I map the gamma's back to the orginal occupations I get very strange results. For example production workers that get assigned topics on management and student/teaching. That's why I went for the assignment command to check what's going on. 
```
assignments <- augment(stmtopic20, 
                            data = tasks_dfm)
assignments %>% 
        filter(document == 80 | document == 81) %>% 
        View()
```
These are two production workers with very similar words to describe their competences:

   |document   |term   |count |topic  
-- | -- | -- | --
1 | 80 | product | 19 | 3
2 | 81 | product | 13 | 3
3 | 80 | assembl | 5 | 2
4 | 81 | assembl | 5 | 2
5 | 81 | transport | 3 | 2
6 | 80 | load | 2 | 7
7 | 81 | load | 2 | 3
8 | 81 | damag | 2 | 3
9 | 80 | goods | 5 | 3
10 | 81 | goods | 5 | 3
11 | 81 | pick | 2 | 3
12 | 80 | concern | 2 | 2
13 | 81 | concern | 2 | 2
14 | 81 | deviat | 2 | 8
15 | 81 | cargo | 1 | 3
16 | 81 | chain | 1 | 3
17 | 81 | circumst | 1 | 3
18 | 80 | condit | 3 | 2
19 | 81 | condit | 2 | 3

However, the important word "product" is assigned to topic 3? Topic 3 has most important words attached: student, pedagog, evalu, pupil, knowledge,... and is clearly about educational content. Topic 10 and 14 have product as their number one word, which seems like the obvious topic. The same for the term "goods": assigned to topic 3 when there is topic 1 that has goods as most important in the beta vector.

Is there anything obvious I am doing wrong here? Is it wrong to feed very similar documents to the algorithm? I thought I would simply get very similar theta's?

Any suggestions welcome. I am new to R, so suggesting I recode something from scratch won't be very helpful for me. Many thanks

**Comment by bstewart** [comment]
Thanks so much for noticing this!  So we didn't write the `augment` or `filter` functions you are using here, they are from tidytext (by the great @juliasilge).  I looked briefly to see what was going on.

@juliasilge thanks so much for writing this, I hadn't really had a chance to dig in.  This is really cool though and I'm always grateful for your writing and kind words about the package.  I only had a couple of quick minutes to work on the code but it looks like there is an error on line 182 of https://github.com/juliasilge/tidytext/blob/master/R/stm_tidiers.R where the beta there is logged. Alternatively I guess this could be fixed on line 176, but somewhere you need to `exp` beta before the product term.  I haven't looked anywhere else so I'm not sure if the error reappears elsewhere.  Also wanted to mention that the documentation for the kind of object returned from augment doesn't match the description in the help file.  Sorry to not go in and do a pull request- running short on time at the moment.

@emiliekuleuven  if you just want the assignments of documents to topics, you want to use `stmtopic20$theta` anyway.  The method to back out the topic assignments by word that is used here works well as a heuristic but because it assigns one topic per word, it will be noisier than the matrix returned from stm.  It can be used for more things though as it is estimated at the per word level.

**Comment by emiliekuleuven** [comment]
@bstewart thanks so much for your fast response. So the reason I started looking at the word assignment is because the theta matrix was making no sense to me. Again, I used the (great) tidytext function to create this: 

```
topiclabel <- sageLabels(stmtopic20, n=3)[[1]]$prob 
colnames(topiclabel) <- c("text1", "text2", "text3")
topiclabel <- topiclabel %>%
  as.data.frame()%>%
  unite(name, c("text1", "text2", "text3"), sep = "_") %>%
  rowid_to_column("topic")

stmtopic20_theta <- tidy(stmtopic20, matrix = "theta") %>%
  filter(gamma>0.001) %>%
  left_join(topiclabel, by = "topic")

stmtopic20_theta %>% 
   filter(document == 80 | document == 81) %>% 
   arrange(document) %>% 
   View()
```
   | document | topic | gamma | name
-- | -- | -- | -- | --
1 | 80 | 3 | 0.397127142 | product_assembl_transport
2 | 80 | 5 | 0.002444823 | product_depart_regist
3 | 80 | 8 | 0.001324246 | customer_commerci_action
4 | 80 | 10 | 0.001892452 | machin_mainten_intervent
5 | 80 | 12 | 0.001571890 | weld_mainten_vehicl
6 | 80 | 14 | 0.006009944 | clean_store_room
7 | 80 | 15 | 0.582138032 | product_goods_depart
8 | 80 | 17 | 0.003340125 | file_document_enter
9 | 81 | 2 | 0.001867082 | child_famili_activ
10 | 81 | 4 | 0.007034941 | council_regul_parent
11 | 81 | 5 | 0.002329161 | product_depart_regist
12 | 81 | 6 | 0.001097480 | photo_take_treat
13 | 81 | 8 | 0.002094146 | customer_commerci_action
14 | 81 | 10 | 0.001184373 | machin_mainten_intervent
15 | 81 | 11 | 0.966748379 | organ_manag_financi
16 | 81 | 13 | 0.003430041 | care_person_need
17 | 81 | 16 | 0.001193146 | materi_instal_yard
18 | 81 | 17 | 0.007181590 | file_document_enter
19 | 81 | 18 | 0.002599210 | anim_treatment_medic

Sorry, when I ran it again the numbering of the topics changed... even though I set.seed. That's confusing, but the words still indicate the same. So for the same person 80 I get high theta on product_assemble_transport and product_goods_depart. Makes sense, but person 81 get's fully assigned to organ_manag_financi, which has zero relevance. 

Again, should I check this by looking at stmtopic$theta? In this matrix, lines represent individual observations ranking by their document ID? And columns are ranked topics?

Many thanks again for your comments!
Emilie

**Comment by bstewart** [comment]
Yeah I'd try to looking at `stmtopic$theta` It is a matrix where each row is a document (in order) and each column is a topic (in order by topic number) and the cell contains the proportion of a document assigned to that topic.  I can try to check the accuracy of the tidy function over the weekend but I'm out of time for today.  

Also I'm not sure why the answer you are getting is different with the seed set to the same.  Something else has gone slightly wrong there.  If you can replicate that problem (preferably with the sample data in the stm package) I'd definitely love to see that so I can track down if there is an issue there.

**Comment by emiliekuleuven** [comment]
Dear Brandon, thank you so much for your suggestions and super fast response. Results from the theta matrix made a lot more sense. So I think something must have gone wrong in the tidytext handling.

I couldn't reproduce the changing numbering of topics with the sample blog data in the stm package. And when I ran it today, it was stable again. So may have been something in the data processing that I changed without realizing it. I am running the code on the full data set now. If I come across the problem again, I will ask again in a separate thread dedicated to this question.

**Comment by juliasilge** [comment]
@emiliekuleuven Thanks for bringing this up, and @bstewart thank you so much for pointing out the `exp()` I missed in the `augment()` function. I added this in the commit referenced above, and went through the other stm tidiers pretty carefully, examining which values were/weren't exponentiated. I am pretty certain that was the only one I had wrong.

If you want to get at the `theta` matrix that Brandon mentioned in a tidy data format, you can do that with `tidy()`, using either `matrix = "gamma"` or `matrix = "theta"`. That gets you the same part of the model output. Some of the other topic modeling frameworks call that per-topic-per-document proportion or probability `gamma`, so you can use either interchangeably in tidytext:

```
tidy(stmtopic20, matrix = "theta")
```
is the same as

```
tidy(stmtopic20, matrix = "gamma")
```

is the same but in a different data structure as

```
stmtopic$theta
```

**Comment by bstewart** [comment]
That's wonderful!  Thanks @juliasilge and @emiliekuleuven.
