### ISSUE TITLE
Interpreting plot.estimateEffect output

### ISSUE THREAD

**Issue by chitbazoo** [bstewart/stm#179]
Hi Brandon, 

I have been working with the stm package to estimate the effect of publication on topic prevalence -- studying how media coverage of the financial crisis varied between British newspaper in the immediate post-crisis era. I've been struggling to correctly interpret some of the output from the plot.estimateEffect(), and wondered if you could provide me with some guidance. I am very new to topic modeling, so I apologise if my description of what I am doing is unclear!

This is my code, modeling topic prevalence as a function of title and date, and content as a function of title, with K=5.
 
```
all_res_k5 <- stm(documents = out$documents, vocab = out$vocab,
                K=5, prevalence = ~ pubtitle_simplified + s(date),
                content = ~ pubtitle_simplified,
                max.em.its = 75, data = out$meta,
                seed=4511648,
                init.type = "Spectral")

k5.effect <- estimateEffect(1:5 ~ pubtitle_simplified + s(date),
                               all_res_k5,
                               meta=out$meta,
                               uncertainty="Global")
```
I have then generated two different plots using the plot.estimateEffect function, first plotting the mean estimated topic proportions for each publication (method="pointestimate") (Plot 1), and second plotting the mean difference in topic proportions between two publications, the Mirror and the Telegraph (method="difference") (Plot 2).

Plot 1:
![image](https://user-images.githubusercontent.com/34513139/49440898-3d11e100-f7c5-11e8-963a-e48ada3e07c8.png)

Plot 2:
![image](https://user-images.githubusercontent.com/34513139/49441046-a8f44980-f7c5-11e8-95af-52d59b444088.png)

 Am I right in interpreting the positive coefficient in Plot 2 as implying that the Mirror (cov.value=1) was relatively more likely to discuss the "Labour/Brown" topic than the Telegraph (cov.value=2) -- or is it the reverse? To me, this seems to be the interpretation that is consistent with Plot 1, but it is not obvious to me how to interpret this output based on the discussion of this function in the documentation.

**Comment by santoshbs** [comment]
@chitbazoo  - your interpretation seems to be correct to me.
