### ISSUE TITLE
searchK not storing models

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#19]
Hi,

is there a reason why `searchK` does fit models and store diagnostics afterwards but not the models themselves? Especially for models which take a lot of time to compute this seems to be suboptimal.

**Comment by bstewart** [comment]
It would be too demanding in terms of memory.  If you want to store them I recommend just writing a loop over the values you want to try.  That's basically all searchK is anyway.

**Comment by methodds** [comment]
Ok I see. Could I then somehow plot the diagnostics for such models without the searchK function? ``plot.searchK()``` does, for example, not accept a vector containing several ``stm models`` as input.

**Comment by bstewart** [comment]
It occurs to me the other reason not to do that is you want to re-estimate
the model with the heldout data back in.   Regardless, the searchK()
function is pretty straightforward under the hood and I think it would be
easy to pull out its contents and run it piecemeal.  It doesn't call any
unexported functions.

I'll try to think about a way to build in some functionality that would
resolve the problem of needing to completely rerun a model produced this
way.

**Comment by bstewart** [comment]
Starting in version 1.2 all of the functions to compute the various metric for searchK are exported functions.  This is documented in the searchK help.
