### ISSUE TITLE
Bug: summary.estimateEffect

### ISSUE THREAD

**Issue by bstewart** [bstewart/stm#194]
Calling for specific topic numbers in the summary function does not correctly index the topics.

**Comment by purityofheart** [comment]
Thanks for the wonderful package!
I was wondering if the following two sets of code will generate the same result:
1) prep <- estimateEffect(1:15 ~ female*gop, PrevFit15, meta = out$meta,
                             uncertainty = "None")
summary(prep, topics = 1)
2) prep1 <- estimateEffect(c(1) ~ female*gop, PrevFit15, meta = out$meta,
                             uncertainty = "None")
summary(prep1)

I think it should but the results are very different using my data. Thanks!

**Comment by bstewart** [comment]
Thanks for flagging this because I need to address this underlying issue.  

I don't think tis the issue you are having.  Could you verify that you are using the latest version on CRAN? If you are, could you send me an example I could reproduce? (feel free to send me an email with the model objects or if you can produce an example using the gadarianFit object?) . I tried to reproduce here and was unable to.

**Comment by purityofheart** [comment]
Thank you for your prompt response!
I've updated the stm package from 1.3.3 to the latest 1.3.5 version and the
multiple topics code seems to produce the same result as the previous
single topic model. However, when I run the summary function after the
single topic model this time, I get the following error message:

Error in object$parameters[[topic]] : subscript out of bounds

Do you know why? I've attached my test dataset and R code. Thanks a lot!

**Comment by purityofheart** [comment]
Btw, the `summary()` for the single topic model works for Topic 1 but not the rest of the topics. Thanks!

**Comment by bstewart** [comment]
I don't think github can take the attachments.  Can you send to me individually?  bms at princeton.edu

**Comment by paskn** [comment]
First of all, thank you for this brilliant tool and all your work! 

I am having the same problem with summary(). In my case, it worked well in 1.3.3. Once I upgraded R and all packages, summary() from version 1.3.5 started acting this way with my object constructed with STM 1.3.3. Also, I can confirm that it works when topics are specified but up to a point. My estimateEffect-object has 46 topics, but summary() stops working on 32nd topic and gives me this error for each remaining topic:  

> Error in object$parameters[[topic]] : subscript out of bounds

I can share code, objects, and more details. Just let me know.

**Comment by paskn** [comment]
Here's a workaround that worked for my case:

**Comment by bstewart** [comment]
I'm sorry this took so long to get to.  Should be fixed in the version that will be up on cran shortly.
