### ISSUE TITLE
s() in stm() prevalence vs. s() in estimateEffect() prevalence

### ISSUE THREAD

**Issue by jeremy-allen** [bstewart/stm#195]
Really loving this package so far. Thank you! My model is failing when I include a s(numeric variable) in the prevalence argument for stm(), but estimateEffect() does not fail when using the same s(numeric variable) in the prevalence argument. 

The numeric variable was originally a column of dates that I converted to numeric before sending to the model. I read in the help documentation that s() takes numeric or factor variables. I cannot figure out why s() in my stm() prevalence fails but works in my estimateEffect() prevalence.

**Comment by vineetbansal** [comment]
Hi Jeremy,
I've been able to run stm() using a spline on a numeric variable. Using the `poliblog5k` data that ships with the package:

```
model <- stm(poliblog5k.docs, poliblog5k.voc, K=10, prevalence=~rating + s(day), data=poliblog5k.meta)
```

If the above line works then it would be a minimal example of getting splines on a prevalence covariate. Can you confirm where exactly it's failing in your case?
