### ISSUE TITLE
Extracting by-topic probability by document  

### ISSUE THREAD

**Issue by rxb230** [bstewart/stm#20]
I am having difficulties finding a command to extract the topic probabilities by document from the topic models I have created. Using the topic topic models package, it can be done like this: 

```{r}

library("topicmodels")
k = 30 # arbitrary number of topics (they are ways to optimise this)
JSS_TM <- LDA(JSS_dtm, k) # make topic model
# make data frame where rows are documents, columns are topics and cells 
# are posterior probabilities of topics
JSS_topic_df <- setNames(as.data.frame(JSS_TM@gamma),  paste0("topic_",1:k))
# add row names that link each document to a human-readble bit of data
# in this case we'll just use a few words of the title of each paper
row.names(JSS_topic_df) <- lapply(1:length(JSS_papers[,1]), function(i) gsub("\\s","_",substr(JSS_papers[,1][[i]], 1, 60)))

``` 

Is there a way to accomplish this using the stm package? 

Kind Regards, 
Rioh

**Comment by bstewart** [comment]
the stm package estimates a different class of topic models than the `topicmodels` package and does not have any functions for working with `topicmodels` objects.  

In ``stm`` if you estimate a model called, for example,  `mod` than `mod$theta` is a matrix where each row is a document and each column is the proportion of the document contained within the column index's topic.

**Comment by rxb230** [comment]
Thank you very much for your response, it is most appreciated. I am currently using your package and I am finding it very useful. Going to try use the matrix output to do some network visualisation. 

Best.
