### ISSUE TITLE
Summary plots and LDAvis conversion

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#21]
Hi,

I noticed some  strange things summary plots  for toLDAvis() results. 

First,  summary plots for STM models do not allow to only show topic proportions with one or zero terms per topic:

````
> plot.STM(model, type='summary', n=1)
Error in FUN(X[[i]], ...) : second argument must be a list
> plot.STM(model, type='summary', n=0)
Error in FUN(X[[i]], ...) : second argument must be a list
````
I think it would be useful if one could also choose to only show proportions without any terms. Even cooler would be a possibility to convert every STM plot into a ggplot, which could then be passed to plotly in one line of code and we have interactive graphs ;-)

Second, if I understand correctly the marginal topic distributions in ````LDAvis```` should be equivalent to the topic proportions for ```STM```, right?

When comparing visualizations this does not seem to be the case:

````
plot.STM(model, type='summary', n=2)
`````
![stm_topicprops](https://cloud.githubusercontent.com/assets/7460499/17461991/153654d2-5c9e-11e6-8bfc-293af9e4be8d.JPG)

````
visout <- toLDAvis(model, out$documents)
prepLDAvis()
````
![ldavis_blobsizes](https://cloud.githubusercontent.com/assets/7460499/17461992/30457fe6-5c9e-11e6-9e90-1411846e5238.JPG)

For example, if you compare the blob sizes of topics 20 and 14, they are quite different to the topic proportions in the STM plot.

An image for reproduction is available [here](https://www.dropbox.com/s/vurp4xfw93vttyw/cdata_bug.RData?dl=0).

**Comment by bstewart** [comment]
Sorry about the very long delay here.

It looks like ldaVis reorders the topics, but from some testing it looks like the word-vocab distributions change with it.  I'm adding a clarification to the documentation.

You are correct about the minimum number of labels.  That would be tricky to change right now for various reasons so I'm going to add a separate issue.  For now I've added documentation.
