### ISSUE TITLE
Character Vectors as Metadata?

### ISSUE THREAD

**Issue by TimBMK** [bstewart/stm#212]
Hey, first of all thank you for this great package! It works like a charm and finds frequent use in my projects.

Lately I'm using it on Twitter data, and I am currently trying to find out whether the models can be improved by using hashtags as metadata. The problem I am running into now is, that the stm function(s) don't like their metadata as character vectors, but rather expect single characters (or other variables) per row. While collapsing the vectors is not a problem, it does beg some methodological questions. For one, chances are that a rather large amount of tweets will have unique combinations of hashtags, basically eliminating any prevalence effects. It also makes effect estimations rather tedious since the unique hashtag combinations make for a very large number of observations in the variable. Right now I'm dealing with these issues by reducing the amount of hashtags used in the model by frequency and sorting the hashtags for each document. This, however, still does not seem optimal to me.

So my question is: Is there a way to feed the model character vectors as metadata that I am not seeing? And if not, are there any plans to implement this functionality in the near future?

**Comment by bstewart** [comment]
Sorry for the delay in responding here.  I think I might not be understanding- perhaps you could offer a concrete example?

I would definitely agree that while you could make a covariate for each individual hashtag, it might not be optimal to do so.  I also wonder if the hashtag should be thought of as part of the message itself (and thus a word token rather than metadata).  Perhaps a more specific example would help though.

**Comment by TimBMK** [comment]
Thanks for the reply, and sorry for taking even longer to respond - the holidays got in the way here.

When converting tweet data into an STM type object (I do so by making a document-feature matrix with quanteda first), and using the original data's hashtag column as metadata, I end up with the data looking like this:
`out$meta$hashtags[7]`

```
[[1]]
[1] "afd"            "cdu"            "grünen"         "ltwbb"          "ltwbrandenburg"
[6] "merkel"         "spd"           
```

That is, a list of character vectors, one of which I printed here. 

However, when trying to run the model, this type of metadata throws the following error:
`stm5 <- stm(documents = out$documents, vocab = out$vocab, K = 5, prevalence =~ hashtags + s(day), data = out$meta, gamma.prior = "L1", init.type = "Spectral" )`
```
Error in makeTopMatrix(prevalence, data) : Error creating model matrix.
                 This could be caused by many things including
                 explicit calls to a namespace within the formula.
                 Try a simpler formula.
```

When collapsing the character vectors, this error is resolved. When doing this, I end up with the following data structure:
`out$meta$hashtags <- vapply(out$meta$hashtags, paste, collapse = " ", character(1L))
out$meta$hashtags[7]`
```
[1] "afd cdu grünen ltwbb ltwbrandenburg merkel spd"
```
While the model now runs fine, this solution creates a problem. Instead of a number of hashtags for each tweet, each of which could potentially be used in the model, I end up with one character string of hashtags for each document. Instead of using, for example, "merkel" as an indicator for a specific topic across all the documents that include the hashtag, I now have a specific set of hashtags for each document. While these may include the same hashtags, most of them boast unqiue combinations, resulting in a very large number of observations for the metadata. It furthermore makes it unlikely the metadata used this way is able to help detect topics, since most documents end up with a unique value for the metadata. By reducing the amount of hashtags beforehand and sorting them for each document I managed to improve the results, but am still not entirely satisfied. What I would like instead is this: being able to treat each unqiue hashtag as a observation of the meta variable "hashtag", even when there are multiple hashtags used in one document.

So to rephrase my question: Is it possible to manipualte the structure of the metadata in a way that is both compatible with the data structure the model expects, and allows to treat each hashtag as a unique value across documents, rather than collapsing them into a unique combination for each document? 

Since the model runs fine after collapsing the vectors, I simply assumed that it expects metadata with one value per document. Reviewing it now, I realize this may not be entirely true and the original metadata's list structure could be the actual problem here. One way or another, I assume the metadata would have to be nested for my purposes, and I am rather unsure what would be the best way to do it, or if it is even possible to run the models like this. 

I hope I could make it a little clearer where my problem lies. Thank you for the support!

**Comment by bstewart** [comment]
Ah I see the problem now. Yeah you can't pass a list object as a piece of metadata and if you collapse you end up with unique combinations.  I would create a set of dummy variables for each hashtag (1 if the document has it, 0 if not). Then these dummy variables can be added as metadata.

**Comment by TimBMK** [comment]
Ah yes, that seems to be a smart way to work around it. I did not think about that before, thanks! 

I am a bit concernd 50+ meta variables might make some trouble down the road though. While I could live with the model running slowly, I am concerned about stability issues. Are any of these to be expected with large amounts of meta variables?

And are there any plans in the development of the package to make list objects feasible as metadata?

**Comment by bstewart** [comment]
I wouldn't worry too much. You can tune the regularization by changing gamma.prior="L1" and playing with some of the options in control.  The content covariate is much more sensitive to the number of categories.

I doubt we will make list objects feasible as metadata.  Unfortunate my list of programming todo's is quite long already!

**Comment by louislegum** [comment]
Hi there, 
I seem to be having a similar issue, I am trying to use a factor with 5 different levels as a metadata variable (country of origin) and I am getting the same error messsage. Do you know a way I might be able to assign dummy variables to the different levels?
