### ISSUE TITLE
How to using ggplot2 for stm effect plot?

### ISSUE THREAD

**Issue by chadchae** [bstewart/stm#22]
Thanks for great package.

I hope to have a effect plot using ggplot.

Is there any solution to get the data for the effect plot for ggplot?

**Comment by bstewart** [comment]
Thanks for the kind words!  If you assign plot.estimateEffect() to an object when you do the plot, the object will contain all the values you need to produce the plot.  You can use these in ggplot however you like

**Comment by chadchae** [comment]
In spite of my limitation of English, I am so appreciate that you gave me a quick and useful response. I am a graduate student in Pennsylvania State University studying in Workforce Education. I see a great potential of this method and package(STM) in education, learning technology, workforce education, Human resource, human resource development field. I will try to do my best work with STM on my study, and hope to share it, communicate about it with you and STM users

Thanks

Chad

**Comment by bstewart** [comment]
Best of luck in your studies!  Happy to help.
