### ISSUE TITLE
Warning for formula with character vector of length > 1

### ISSUE THREAD

**Issue by juliasilge** [bstewart/stm#222]
I am seeing some warnings in the tests for tidytext because of the way this line is set up:

https://github.com/bstewart/stm/blob/c95ef0ba551332d6b8cfd44e789308b4fc1482df/R/estimateEffect.R#L146

The warning is:

```
Warning message:
Using formula(x) is deprecated when x is a character vector of length > 1.
  Consider formula(paste(x, collapse = " ")) instead. 
```

Looks like this was [considered a bug fix in R 4.0](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html):

> formula(x) with length(x) > 1 character vectors, is deprecated now. Such use has been rare, and has ‘worked’ as expected in some cases only. In other cases, wrong x have silently been truncated, not detecting previous errors.

**Comment by stragu** [comment]
All three examples from `stm::estimateEffect()` have the same warning:

``` r
library(stm)
#> stm v1.3.5 successfully loaded. See ?stm for help. 
#>  Papers, resources, and other materials at structuraltopicmodel.com
prep <- estimateEffect(c(1) ~ treatment, gadarianFit, gadarian)
#> Warning: Using formula(x) is deprecated when x is a character vector of length > 1.
#>   Consider formula(paste(x, collapse = " ")) instead.
prep <- estimateEffect(1:3 ~ treatment, gadarianFit, gadarian)
#> Warning: Using formula(x) is deprecated when x is a character vector of length > 1.
#>   Consider formula(paste(x, collapse = " ")) instead.
prep <- estimateEffect(1 ~ treatment*s(pid_rep), gadarianFit, gadarian)
#> Warning: Using formula(x) is deprecated when x is a character vector of length > 1.
#>   Consider formula(paste(x, collapse = " ")) instead.
```

<sup>Created on 2020-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'm seeing the same in `ordinal::clmm()` when using a long formula, not sure if that helps figuring it out:

``` r
library(ordinal)
data(wine)
# no warning:
mm <- clmm(rating ~ temp + contact + (1|judge),
           data = wine)
names(wine)[2] <- "a_very_very_very_very_very_long_name"
# warning:
mm <- clmm(a_very_very_very_very_very_long_name ~ temp + contact + (1|judge),
           data = wine)
#> Warning: Using formula(x) is deprecated when x is a character vector of length > 1.
#>   Consider formula(paste(x, collapse = " ")) instead.
```

<sup>Created on 2020-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Looking very odd to me!

**Comment by stgries** [comment]
Just echoing stragu with regard to the warning in `ordinal::clmm`.

This model

`m <- clmm(JUDGMENT ~ 1 + NATIVE_LG * AGREEMENT + EMPHPRON + NEGATION + (1|SUBJECT), data=x)`

runs fine but throws a warning message

    Using formula(x) is deprecated when x is a character vector of length > 1.
      Consider formula(paste(x, collapse = " ")) instead.`

but if the last predictor is deleted, then it works without problems:

`m <- clmm(JUDGMENT ~ 1 + NATIVE_LG * AGREEMENT + EMPHPRON + (1|SUBJECT), data=x)`

Not sure how that bug fix even pertains to this issue ... weird

**Comment by stragu** [comment]
Ji @stgries ! If you want to chat about `clmm()` specifically, I reported the issue here, just so you know: https://github.com/runehaubo/ordinal/issues/34
Cheers

**Comment by bstewart** [comment]
Got this fixed.  Sorry development has been on hold for a bit everyone.  Thanks @juliasilge for flagging.
