### ISSUE TITLE
spectral init optimization (accidentally?) didn't make it into 1.3.4

### ISSUE THREAD

**Issue by brooksambrose** [bstewart/stm#226]
https://github.com/bstewart/stm/blob/c95ef0ba551332d6b8cfd44e789308b4fc1482df/inst/NEWS.Rd#L8-L12

Thanks for the shout out! However, I'm noticing that my optimization didn't actually make it into 1.3.4 as advertised, so is still only on the development branch.

Blame on current CRAN version lists the line in question as dating back to version 1.2.1:

https://github.com/cran/stm/blame/a1cdeb7ce00ab99f907fc1b728cd0d14f4872573/R/spectral.R#L20

Old line is:

https://github.com/bstewart/stm/blob/c95ef0ba551332d6b8cfd44e789308b4fc1482df/R/spectral.R#L20

Optimization is:

https://github.com/bstewart/stm/blob/767d2e6f7b97208ef28d14a07da8144351a52a06/R/spectral.R#L20

Relevant PR was #176.

**Comment by bstewart** [comment]
Oh yikes- thanks so much.  I'm very behind on development for stm and hoping to do a big push on it soon.  Will fold this in.  Not entirely sure how I missed that.  Really appreciate you flagging.

**Comment by bstewart** [comment]
Sigh wow did this take a while.  It is in there now and going up on CRAN.  Sorry life has been crazy.  Thanks again for finding this and then finding it again.

**Comment by brooksambrose** [comment]
I appreciate you!
