### ISSUE TITLE
Lemmatization with stm package

### ISSUE THREAD

**Issue by gbganalyst** [bstewart/stm#227]
I understanding that 

`stm::textProcessor(documents, metadata = NULL, lowercase = TRUE,
  removestopwords = TRUE, removenumbers = TRUE,
  removepunctuation = TRUE, ucp = FALSE, stem = TRUE,
  wordLengths = c(3, Inf), sparselevel = 1, language = "en",
  verbose = TRUE, onlycharacter = FALSE, striphtml = FALSE,
  customstopwords = NULL, custompunctuation = NULL, v1 = FALSE)`

allows for stemming.

Is there a way to do lemmatization of words in stm package?

**Comment by bstewart** [comment]
There isn't but we strongly recommend quanteda.  `textProcessor` was really defined as a convenience function and not as a particularly customizable framework.  quanteda is great for this kind of stuff and plays nicely with stm.

**Comment by gbganalyst** [comment]
Thank you for the quick response. How do we include those metadata with quanteda so that stm can play nicely with it?
