### ISSUE TITLE
searchK

### ISSUE THREAD

**Issue by ftt80** [bstewart/stm#23]
Hello,

First of all, thank you for the package!

I have a corpus of about 10.000 documents with a mean length of about 6.000 characters (not words). In order to determine the number of topics I ran searchK over a wide range of possible numbers from 5 to 400. 

The issue is that coherence is at its highest value at 5 topics (which is too low) while the heldout likelihood as well as exclusivity seems to monotonically increase in K.

Looking at the data it seems odd to me that the two indicators go into opposite directions. From a substantive point of view 5 topics seem to be far too low while 400 are too many.

I wonder if this is kind of a common issue and if there is a way to handle it.

Thanks in advance,
ftt

**Comment by bstewart** [comment]
Yeah we've seen a lot this unfortunately.  It likely just a fairly complex document set.  The problem with semantic coherence as applied here is that its a measure for topic quality and not overall model quality.  Thus it isn't clear that the average of those values (which we report in searchK) should necessarily have favorable properties.

For what its worth I have generally strongly recommended a qualitative approach to these things.  searchK is present as a convenience for those who want a heldout likelihood or other statistic driven approach, but I would advocate finding the level of granularity that is appropriate for your research question and selecting on the basis of that.

**Comment by ftt80** [comment]
Thanks for your quick answer! 

This is somewhat reassuring for me.
