### ISSUE TITLE
searchK error

### ISSUE THREAD

**Issue by remTene** [bstewart/stm#231]
Hi!

I have already used searchK, but now it gives me always the same error:

`storage <- searchK(out$documents, out$vocab, K = c(8,2,4,7,9), prevalence =~ status,data= out$meta, init.type = "Spectral")`
`Error in missing$docs[[i]] : index out of range`

I've reinstalled stm form Github and processed the data with textProcessor.

**Comment by asdurso** [comment]
Did you ever figure this out? I am having the same issue and cannot find a solution anywhere.

**Comment by remTene** [comment]
Yes. If I remember correctly, it was due to a wrong formatting of `out` components

**Comment by asdurso** [comment]
Thank you... Hoping I can get there! :-)

**Comment by asdurso** [comment]
For anyone else who has this problem: I had to stipulate N--the number of docs to be partially held out.
