### ISSUE TITLE
Question about the parameter estimation strategy

### ISSUE THREAD

**Issue by yeyzh** [bstewart/stm#238]
Hello, thanks for your excellent package. 
I have a question about the parameter estimation strategy. I use getAnywhere to detect the function _estimateEffect_, and I found the estimation model is _lm_ if I understand correctly. However, along with the huge size of text data, it might be too easy for users to get significant results when they explore covaraites. I wonder whether you could introduce some other parameter estimations which are more appropriate to handle a large sample size or just I ignore them? Thanks!

**Comment by bstewart** [comment]
I guess I don't quite understand what exactly you are looking for here.  But you can always write post estimation routines yourself!  All the details of how we do the post-estimation are in the _JSS_ and _AJPS_ papers.
