### ISSUE TITLE
Number of topics, perflexcity 

### ISSUE THREAD

**Issue by chadchae** [bstewart/stm#25]
Comment on the last issues was big help.
I run the search K, and model diagnostics.

So based on highest heldout likelihood, I decided number of topics.

As I know there are some other indicator for decide number of topic such as perplexity. 

Is there specific function or way to calculate perplexity from stm package or stm generated object?

**Comment by bstewart** [comment]
Glad it was helpful.  Perplexity is a deterministic transformation of heldout likelihood so it will yield the same answer.
