### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by Dementiy** [bstewart/stm#38]
Hi,

I have 86k short documents (but larger than 50 characters) and I got an error about integer overflow:

```
> processed <- textProcessor(data$documents, metadata = data,
 verbose = T, lowercase = F, removestopwords = F, removenumbers = F, removepunctuation = F, stem = F)
Building corpus... 
Creating Output... 
Warning messages:
1: In nr * nc : NAs produced by integer overflow
2: In nr * nc : NAs produced by integer overflow
3: In nr * nc : NAs produced by integer overflow
4: In nr * nc : NAs produced by integer overflow
```

I use stm from CRAN (1.1.3)
How much documents `stm` can handle?

P.S. I reduced the number of documents, but got another error after `prepDocuments`:
```
Error in stm(out$documents, out$vocab, K = 15, ... : 
  number of observations in content covariate (34086) prevalence 
  covariate (32733) and documents (34086) are not all equal
```

**Comment by bstewart** [comment]
Something is a bit odd here. 

Two suggestions:
(1) if you wouldn't mind sharing I would love to get a copy of the data that produced the error to test with.  If you don't want to post here, feel free to send me an email.  I imagine something here is a bit idiosyncratic, but if I could play around with it- i imagine I could add some more informative error messages.
(2) I'd recommend using quanteda (https://github.com/kbenoit/quanteda) to do your text processing.  They have a function that will export to the stm format.  It is an entire package built to do text processing and is a lot more robust than the simple textProcessor() function which is really just a convenience wrapper.  This should resolve even your postscript error as that one suggests there is something wrong with the inputs.

**Comment by Dementiy** [comment]
With version 1.1.5 I have no problem with textProcessor() function, but prepDocuments() still not working. And R session crashes when I try to build a model (stm), I guess that I have not enough memory.
Link to my [dataset](https://github.com/Dementiy/vkR/blob/master/examples/cmnts_df_prepared.csv).

**Comment by bstewart** [comment]
Sorry for the slow response here.  Thanks so much for sharing your data.

I was not able to replicate the error with prepDocuments.  My guess is that the R session crashes because without running prepDocuments() the vocab size is 1.7 million.  One of the first things stm does is instantiate a matrix with K (number of topics) rows and number of columns equal to the vocab size.  That means 1.7 million will kill even extremely high memory machines.

What caused prepDocuments to fail?  Was it also a memory thing?  One option would be to use the sparselevel option in textProcessor().  If you set it to .999 (i.e. the word must only appear in one tenth of one percent of the documents, you drop your vocab down to around 4000 terms and everything goes much quicker!)

**Comment by Dementiy** [comment]
Thanks for your response. 

I have no more troubles with `textProcessor()` function (thanks for the `sparselevel`), but I still have problems with `prevalence`.
If I run this code:
```
fit <- stm(out$documents, out$vocab, K = 15, 
           prevalence =~ likes_count + group_name,
           max.em.its = 75, data = out$meta, init.type = "Spectral")
```
everything is OK. But when I add `sex` feature I got an error:

```
Error in stm(out$documents, out$vocab, K = 15, prevalence = ~likes_count +  : 
  number of observations in content covariate (109775) prevalence covariate (105963) and documents (109775) are not all equal.
```

And I don't know why, because variables have the same length:

```
> sapply(out$meta, length)
  documents  group_name likes_count         sex         age 
     109775      109775      109775      109775      109775
```

`sex` is a factor variable and having only two levels: `male` and `female`. `group_name` is also factor variable, but with more levels.

**Comment by bstewart** [comment]
You might check if sex has any missing data.  My guess is it does (or one of the variables does).  If that's not the issue maybe you could share an example dataset and I could look into it.

**Comment by Dementiy** [comment]
Yes, you are right, `sex` has missing values. My fault, thanks.

**Comment by bstewart** [comment]
No worries- I appreciate the question as it made me realize I should add an error message to more clearly signal that.  I haven't yet but I will on issue #39

**Comment by ryp33** [comment]
Hi Dementiy and bsteward. Currently facing the same issue. 
> sapply(out$meta, length) shows all the same length. 
How did you solve this?

Thanks in advance
