### ISSUE TITLE
Question: Development branch stability

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#41]
Hi Brandon,

is the code in the developmental branch stable enough to use? As far as I understand the fix for #16 is not yet in the master branch right?

**Comment by bstewart** [comment]
It is stable (although please let me know if you find anything-  I'm still tweaking and testing).  (also you are correct it isn't in the master yet)

**Comment by methodds** [comment]
Alright, thanks for the info. I'll let you know in case I run into any problems. I guess this can be closed then.

**Comment by methodds** [comment]
I found something for which I'm not sure whether it was like this before. When plotting a ``stm`` object with ``type='perspectives'``, setting ``labeltype='frex'`` does not seem to have any effect. Is this new? Or does this have computational reasons? From that I understand the frex metric could also be used for perspective plots, where the exclusivity difference between two topics for a term would be the position on the x axis.

If this does not make any sense, it might be useful to note in the documentation of ``plot.STM`` that ``labeltype`` will not effect ``perspective`` plots.

**Comment by bstewart** [comment]
Hmmm... thanks I'll look into this.

**Comment by bstewart** [comment]
Great.  Clarified this only works for highest probability words.

Hypothetically you could use FREX in a similar plot but the way the plot is currently designed it doesn't use any of the labeling methods directly.  The pieces of the plot are determined directly from the word probability matrix.  This is now clearer in the documentation.

**Comment by bstewart** [comment]
Please feel free to reopen if you find any new problems!
