### ISSUE TITLE
stm freezes during E-step

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#45]
Hi,

with the recent development version of stm, fitting a model always freezes during the E-step when including a specific factor covariate. 
This works just fine:
```
library(stm)

stm14g <- stm(documents=prep_stm_14g$documents, vocab=prep_stm_14g$vocab, 
data= prep_stm_14g$meta,
               init.type='Spectral', K=5, prevalence=~ s(day))
```
And this always freezes:
```
stm14g <- stm(documents=prep_stm_14g$documents, vocab=prep_stm_14g$vocab, 
data= prep_stm_14g$meta,
               init.type='Spectral', K=5, prevalence=~ s(day) + topic_id)
```
Whenever I keyboard interrupt after a freeze, there's another arbitrary error raised everytime. Including the covariate in the model does not make much sense here, as its basically just an identifier for each document. But I guess stm should still not just freeze without an error.
Please find a file for reproduction [here](https://dl.dropboxusercontent.com/u/22352379/STM_covariatebug.RData).

**Comment by methodds** [comment]
And with the same reproduction file you should be able to reproduce another bug:

```
> length(prep_stm_14g$vocab)
[1] 5936


K<-c(50) 
kresult <- searchK(documents=prep_stm_14g$documents, vocab=prep_stm_14g$vocab, data= prep_stm_14g$meta,
               init.type='Spectral', K, prevalence=~ s(day, degree=2) )

eginning Initialization.
 Show Traceback
Error in stm.init(documents, settings) : Spectral initialization cannot be used for the overcomplete case (K greater than or equal to number of words in vocab)
```

**Comment by bstewart** [comment]
Fantastic.  Thanks for these.  I'm really looking forward to digging into that first one.  That is an unexpected place to have an error from that...

**Comment by bstewart** [comment]
Okay I've addressed these errors in the development branch.  Thanks!
