### ISSUE TITLE
searchK with a large number of documents

### ISSUE THREAD

**Issue by towashington** [bstewart/stm#47]
Hi, I encountered the following problem with searchK and wonder if anyone could shed some light on the possible causes. Thanks in advance!

I have a corpus that, after implementing prepDocuments, contains about 1.3 million documents, three thousand terms, and 15 million tokens. Then, when I used searchK, it shows an error during "Recovering initialization..." The error says: "Error in t.default(La.res$vt) : argument is not a matrix."

Could this be because the corpus is too large? When I test-ran it with a small subset of one thousand documents, it worked out smoothly without an errors...

Thank you!

**Comment by bstewart** [comment]
Interesting....I don't know what's happening here.  Any chance you could send me a dropbox link with replication code and data?  The way that error reads it doesn't seem like a size thing.
