### ISSUE TITLE
Parallelization of stm?

### ISSUE THREAD

**Issue by nickbadams** [bstewart/stm#5]
Thank you for making this wonderful package available to the research community! Do you have and script to parallelize stm? Any plans on this front? Thanks, again!

**Comment by bstewart** [comment]
Thanks!  It is something we are working on- it is just a matter of finding something that works well across many different systems.

If you have a lot of memory you can use the option ngroups  set to an integer greater than 1.  This doesn't parallelize per se but interweaves global updates with the document-level updates which can speed convergence.

**Comment by nickbadams** [comment]
Great! Thanks! I'll try ngroups. And if you have some script that you think
works in a Linux environment, I can try to test it out on a NERSC
<https://www.nersc.gov/> allocation and report back(?). Cheers!

On Thu, Feb 5, 2015 at 11:08 AM, Brandon Stewart <notifications@github.com>
wrote:

> Thanks! It is something we are working on- it is just a matter of finding
> something that works well across many different systems.
>
> If you have a lot of memory you can use the option ngroups set to an
> integer greater than 1. This doesn't parallelize per se but interweaves
> global updates with the document-level updates which can speed convergence.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bstewart/stm/issues/5#issuecomment-73106342>.
>



-- 
*Nick Adams*
* Data Science Fellow, **Berkeley Institute for Data Science
<http://vcresearch.berkeley.edu/datascience/people>*
* Instructor / Consultant, **D-Lab  <http://dlab.berkeley.edu/>*
* Principal Investigator, **The Deciding Force Project
<http://www.decidingforce.com>*

**Comment by bstewart** [comment]
Thanks!  I may take you up on that at some point.

**Comment by nickbadams** [comment]
Great! I should say, too: if you or anyone from your team is ever in the
Bay Area, we'd love to have you give a talk at Berkeley's Institute for
Data Science <http://bids.berkeley.edu> or it Social Science Data Lab
<http://dlab.berkeley.edu/>. You have a fan base, here!  :)   All best,

Nick

On Thu, Feb 5, 2015 at 11:21 AM, Brandon Stewart <notifications@github.com>
wrote:

> Thanks! I may take you up on that at some point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bstewart/stm/issues/5#issuecomment-73108590>.
>



-- 
*Nick Adams*
* Data Science Fellow, **Berkeley Institute for Data Science
<http://vcresearch.berkeley.edu/datascience/people>*
* Instructor / Consultant, **D-Lab  <http://dlab.berkeley.edu/>*
* Principal Investigator, **The Deciding Force Project
<http://www.decidingforce.com>*

**Comment by bstewart** [comment]
Thanks!  That would be amazing. I'll definitely let you know if we are out that way.

**Comment by lieove** [comment]
it's wonderful. And I try to use DMR topic model, but i find there is something wrong with the parameter init.type of manyTopics function. 
like this:
Error in match.arg(init.type) : 
  'arg' should be one of "LDA", "Random", "Spectral"
I install the latest version 1.0.12.
Why? Hope you can help me. Thanks!

**Comment by nickbadams** [comment]
Hey Brandon,

Using stm package now. I couldn't find a specific answer to this in your
documentation:

*How do I find the seed of the model that I like, so I can re-run it later?*


Sorry if I just missed this.

Best,

Nick



On Thu, Apr 30, 2015 at 10:23 AM, lieove <notifications@github.com> wrote:

> it's wonderful. And I try to use DMR topic model, but i find there is
> something wrong with the parameter init.type of manyTopics function.
> like this:
> Error in match.arg(init.type) :
> 'arg' should be one of "LDA", "Random", "Spectral"
> I install the latest version 1.0.12.
> Why? Hope you can help me. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bstewart/stm/issues/5#issuecomment-97886917>.
>



-- 
*Nick Adams*
* Data Science Fellow, **Berkeley Institute for Data Science
<http://vcresearch.berkeley.edu/datascience/people>*
* Instructor / Consultant, **D-Lab  <http://dlab.berkeley.edu/>*
* Principal Investigator, **The Deciding Force Project
<http://www.decidingforce.com>*

**Comment by bstewart** [comment]
Let's say your object is called "mod"

mod$settings$seed

contains the seed.  Pass this to the argument "seed" in stm()

**Comment by nickbadams** [comment]
Thanks, Brandon!!


On Sat, Jun 13, 2015 at 2:54 PM, Brandon Stewart <notifications@github.com>
wrote:

> Let's say your object is called "mod"
>
> mod$settings$seed
>
> contains the seed. Pass this to the argument "seed" in stm()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bstewart/stm/issues/5#issuecomment-111755089>.
>



-- 
*Nick Adams*
* Data Science Fellow, **Berkeley Institute for Data Science
<http://vcresearch.berkeley.edu/datascience/people>*
* Instructor / Consultant, **D-Lab  <http://dlab.berkeley.edu/>*
* Principal Investigator, **The Deciding Force Project
<http://www.decidingforce.com>*
