### ISSUE TITLE
outputdata can return vector of length > 1

### ISSUE THREAD

**Issue by APuzyk** [bstewart/stm#55]
outputdata (in produce_cmatrix.r) returns the median or mode of a variable depending on type.

If we have a character or factor vector with 2+ levels with the same number of observations outputdata will return all those levels.

Ultimately this leads to an issue since either cdata will not have the same number of rows as the output or more importantly we'll have different values for the controls.

**Comment by bstewart** [comment]
Oh wow- great catch.  I'll work on this.  Glad you found this!
