### ISSUE TITLE
Johannes

### ISSUE THREAD

**Issue by Ledolter** [bstewart/stm#56]
Any reason why permutationTest does not work? Thanks 

temp<-textProcessor(documents=gadarian$open.ended.response,metadata=gadarian)
out <- prepDocuments(temp$documents, temp$vocab, temp$meta)
documents <- out$documents
vocab <- out$vocab
meta <- out$meta
set.seed(02138)
mod.out <- stm(documents, vocab, 3, prevalence=~treatment + s(pid_rep), data=meta)
summary(mod.out)
prep <- estimateEffect(1:3 ~ treatment + s(pid_rep), mod.out, meta)
plot(prep, "treatment", model=mod.out,
method="difference",cov.value1=1,cov.value2=0)
test <- permutationTest(formula=~ treatment + s(pid_rep), stmobj=mod.out,
treatment="treatment", nruns=25, documents=documents,
vocab=vocab,data=meta, stmverbose=FALSE)
plot(test,2, xlab="Effect", ylab="Model Index", main="Topic 2 Placebo Test")

**Comment by bstewart** [comment]
It works on my machine.  You are missing the tilde in front of the formulas for prevalence in the stm command and the formula argument in permutationTest

**Comment by Ledolter** [comment]
Brandon:    Hmm ….

When I run the code from your vignette on my computer, it does not work. I get the following output …

> temp<-textProcessor(documents=gadarian$open.ended.response,metadata=gadarian)
Building corpus...
Converting to Lower Case...
Removing stopwords...
Removing numbers...
Removing punctuation...
Stemming...
Creating Output...
> out <- prepDocuments(temp$documents, temp$vocab, temp$meta)
Removing 619 of 1074 terms (619 of 3731 tokens) due to frequency
Your corpus now has 341 documents, 455 terms and 3112 tokens.> documents <- out$documents
> vocab <- out$vocab
> meta <- out$meta
> set.seed(02138)
> mod.out <- stm(documents, vocab, 3, prevalence=~treatment + s(pid_rep), data=meta)
Beginning Initialization.
.................................................................................................................
Completed E-Step (0 seconds).
Completed M-Step.
Completing Iteration 1 (approx. per word bound = -5.529)

> summary(mod.out)
A topic model with 3 topics, 341 documents and a 455 word dictionary.
Topic 1 Top Words:
         Highest Prob: peopl, come, think, get, work, border, countri
         FREX: come, get, work, better, like, mexican, much
         Lift: build, control, day, like, mexican, noth, work
         Score: peopl, come, think, work, get, better, life
Topic 2 Top Words:
         Highest Prob: job, illeg, tax, pay, take, english, american
         FREX: tax, secur, care, welfar, languag, social, health
         Lift: caus, etc, health, lack, loss, lost, social
         Score: job, social, tax, welfar, servic, cost, loss
Topic 3 Top Words:
         Highest Prob: immigr, illeg, legal, countri, will, need, worri
         FREX: immigr, will, worri, nation, state, usa, worker
         Lift: almost, although, amongst, attitud, bit, boarder, built
         Score: immigr, worri, will, countri, mexico, nation, legal
> prep <- estimateEffect(1:3 ~ treatment + s(pid_rep), mod.out, meta)
> plot.estimateEffect(prep, "treatment", model=mod.out,
+                     method="difference",cov.value1=1,cov.value2=0)
> test <- permutationTest(formula=~ treatment + s(pid_rep), stmobj=mod.out,
+                         treatment="treatment", nruns=25, documents=documents,
+                         vocab=vocab,data=meta, stmverbose=FALSE)
Calculating effects for reference model
Running model 2 of 25
Error in stm.control(documents, vocab, settings = settings) :
  argument "model" is missing, with no default
> plot.STMpermute(test,2, xlab="Effect", ylab="Model Index", main="Topic 2 Placebo Test")
Error in plot.STMpermute(test, 2, xlab = "Effect", ylab = "Model Index",  :
  object 'test' not found
>

While I have this question, may I please ask some more …

Question 2: I am running

results20=stm(ccc$documents,ccc$vocab,K=3,prevalence=~factor(ids2),max.em.its=100,init.type="Spectral")
labelTopics(results20,c(1,2,3))

Works fine. But for some reason, cloud doesn’t work. However, it DID work yesterday. Not sure why or why not?

cloud(results20)
cloud(results20,1)

Question 3:
Is there a way to test the significance of the prevalence meta variable (in results20). I realize the problem with the p-value … but is there a way to at least get it?

Question 4: I am coming from the tm package. Within tm, I have read in the corpus and I have created the dtm matrix. I am transferring this matrix into the format that is needed for stm.  [ccc=readCorpus(corpus.dtm, type = c("slam"))            ## converts dtm matrix into stm]. This works. I also have a file for the corpus (again created with the tm package).

I would like to use the findThoughts function (as this is useful). But what do I have to do with the corpus to make this work..

Lots of questions. I hope I am not a bother.

Thanks

Hannes

Johannes Ledolter
University of Iowa

**Comment by bstewart** [comment]
Re: Q1)  
I suspect you are using an old version of the package.  Please ensure you are using Version 1.2.1 by running sessionInfo().  I did confirm this works on the newest build.

Re: Q2)
I don't know what would make it work one day and not the next.  I would recommend clearing your workspace, reloading R and then trying again.

Re: Q3)
You can run estimateEffect() and then run summary() on the resulting object.  This will yield a table with p-values.

Re: Q4)
You need a vector where each element is the text of the document.  I'm sure you can extract this from the tm corpus but you might have to google around to figure out how.

**Comment by Ledolter** [comment]
Thanks for the very quick feedback.

About Q1 (permutation test from your vignette):
I was using stm_1.1.3. Now I switched to 1.2.1 [the Iowa download hub must have had an older version, because when I updated stm, it still gave me 1.1.3. Not sure why]

Now the calculations work.
But now it can’t find the plotting routines
> plot.estimateEffect(prep, "treatment", model=mod.out,
+                     method="difference",cov.value1=1,cov.value2=0)
Error: could not find function "plot.estimateEffect"
> plot.STMpermute(test,2, xlab="Effect", ylab="Model Index", main="Topic 2 Placebo Test")
Error: could not find function "plot.STMpermute"

In fact, it can’t find most of the plotting functions suich as
plot.topicCorr(mod.out.corr)## for displaying the correlation among topics
plot.STM(results20,type="summary")

Was there a change??


About Q1 on cloud:
I have done what you suggested, starting from scratch and clearing the workspace. The problem with cloud is still there. Here is the error message

> cloud(results10,max.words=15)
Error in UseMethod("cloud") :
  no applicable method for 'cloud' applied to an object of class "STM"

**Comment by bstewart** [comment]
Yes. These functions are now referred to using their generic names.  So just change plot.whatever() to plot().  See the NEWS file or the vignette.

You have some other package loaded that defines a generic cloud.  I don't know what it is, but if you just do stm::cloud(results10)  it will make it unambiguous what you mean and should work.

**Comment by Ledolter** [comment]
Brandon

Thanks so much.
I also see the p-values for the meta variables (for prevalence) using the summary function. Minor point: I am actually having a factor meta variable and was looking for the p-value for the overall (F-type) test.
Your help is much appreciated!!!
Hannes

I like the stm library. I will play around with it in more detail. When working with the LDA function in tm, I learned that the parameters in the Dirichlet priors can have quite an influence on the results. You have lots of experience with stm … do you see similar issues?

I visited at Chicago Booth in 2011 and 2012 at a time when Matt Taddy was working on text data. I was aware of his multivariate normal for the logits which is an important component in your model.

**Comment by bstewart** [comment]
Yeah we don't have specific f-tests in there but it would be easy enough to work out from the output.  In terms of hyperparameters- STM optimizes them (the general advice per Wallach et al 2009).  This is a happy byproduct of the covariate based infrastructure.

One theory for why hyperparameters matter is because they nudge the algorithm to a better local solution.  We have an approach that is even better based on initialization with a spectral algorithm.  We describe in this paper (http://scholar.harvard.edu/files/dtingley/files/multimod.pdf) see in particular the penultimate section.

**Comment by Ledolter** [comment]
Brandon:

Sorry to bother you with a question, but I would really like to understand the details and I can’t find answers in the documents.

This time it is about the semantic coherence score in the plot of selectModel results. I understand that the semantic coherence score has to do with co-occurrence. The way the measure is defined makes this measure negative, and I believe it has an upper bound of -(N*(N-1)/2)log(2) where N is the number of words. The larger the measure, the larger the coherence. But we know little about what values to expect. The measure appears to be a function of the number of words.

I have questions about your plot on page 12 of your paper in the Journal of Statistical Software. (1) I am unsure whether the coherence measure for a given topic is calculated from the 10, or 20, or ?? most common words, or ALL words. Doing it for ALL words would be very time-consuming and I am not sure whether it would make sense. (2) Is it correct that coherence calculations are not done on any estimated parameters from the model fit, but on actual counts of co-occurrence in the corpus. It’s just a matter of counting! (3) About average exclusivity in this graph. This seems to be based on estimated parameters (probabilities) from the model. The same question arises here whether the value for a given topic is the average from the most common 10 (20, ?) words or on ALL words?

Thanks a lot
Hannes

**Comment by bstewart** [comment]
Re: 1) It is the top 10 most probable words for the topic (a number you can set in the function see: ?semanticCoherence).  
Re: 2) you are correct, its just counting given the set of most probable words (which are based on model parameters)
Re 3) Exclusivity is also based by default on the 10 most probable words (?exclusivity).

**Comment by Ledolter** [comment]
Thanks a lot. Hannes

**Comment by Ledolter** [comment]
Brandon: About probability, FREX, lift and score. I think I got this right, but I always stand corrected. Thanks, as always. Hannes

**Comment by bstewart** [comment]
No worries- happy to help!

**Comment by Ledolter** [comment]
Brandon:

You have been very helpful answering questions in the past. May I bother you with another query. It has to do with the estimateEffect function.

I am fitting a 3-topic model without any meta data.

results10=stm(ccc$documents,ccc$vocab,K=3)  ## no meta
results10$mu     ## shows that it just estimates the two means

ids2 is a meta variable, with five categorical outcomes. When using estimateEffect as shown below (with simulations from results10), I was expecting to see no significance of the meta variable. But I see strong significance. Where did I go wrong?
I thought that the statement below would simulate document-specific topic probabilities from results10 (50 such reps), and when relating (regressing) these probabilities on the five groups there should not be any relationship to the variable factor(ids2).

prep <- estimateEffect(1:3~factor(ids2),results10,nsims=50)
summary(prep)                ## assesses significance of meta variables
par(mfrow=c(1,1))
plot(prep,"ids2")

**Comment by Ledolter** [comment]
May I follow up with another question.
You are estimating the model on EACH simulation. If there are 50 simulations, you get 50 sets of regression coefficients. Then you summarize the results when executing summary(.).
How do you get to the summary results? Especially the standard errors? Are you using Zellner’s SUR estimation approach?
Thanks
Hannes

From: Ledolter, Johannes
Sent: Tuesday, May 02, 2017 1:11 PM
To: 'bstewart/stm' <reply@reply.github.com>; bstewart/stm <stm@noreply.github.com>
Cc: Author <author@noreply.github.com>; Ledolter, Johannes <johannes-ledolter@uiowa.edu>
Subject: RE: [bstewart/stm] Johannes (#56)

Brandon:

You have been very helpful answering questions in the past. May I bother you with another query. It has to do with the estimateEffect function.

I am fitting a 3-topic model without any meta data.

results10=stm(ccc$documents,ccc$vocab,K=3)  ## no meta
results10$mu     ## shows that it just estimates the two means

ids2 is a meta variable, with five categorical outcomes. When using estimateEffect as shown below (with simulations from results10), I was expecting to see no significance of the meta variable. But I see strong significance. Where did I go wrong?
I thought that the statement below would simulate document-specific topic probabilities from results10 (50 such reps), and when relating (regressing) these probabilities on the five groups there should not be any relationship to the variable factor(ids2).

prep <- estimateEffect(1:3~factor(ids2),results10,nsims=50)
summary(prep)                ## assesses significance of meta variables
par(mfrow=c(1,1))
plot(prep,"ids2")

**Comment by bstewart** [comment]
To the question one thread up: why do you expect to get no relationship with the metadata?  I'm not sure I follow your confusion.

On the 2 means thing- the 3 topic model is constrained to the simplex (non-negative values summing to one) so two numbers describes all three topics.

To get the coefficients and standard errors we do the following.  For each simulation draw from a multivariate normal centered at the ols estimates with the estimated variance-covariance matrix.  We take a number of draws (500 by default) for each simulation.  We then collect them all together and summarize that full distribution.  It is based on the approach described in this paper: https://gking.harvard.edu/files/gking/files/making.pdf

**Comment by Ledolter** [comment]
My model that generates the probability assignments for the K letters doesn't know anything about the meta variable. So the generated topic probabilities from that model for the K letters  should be independent and not related to the meta variable ....

I'll read the reference. But I am puzzled by the fact that you present the model estimates for each simulation, and then also the summary with the standard errors. Puzzled how you get those

Thanks

Hannes

Sent from my iPhone

On May 2, 2017, at 5:02 PM, Brandon Stewart <notifications@github.com<mailto:notifications@github.com>> wrote:


To the question one thread up: why do you expect to get no relationship with the metadata? I'm not sure I follow your confusion.

On the 2 means thing- the 3 topic model is constrained to the simplex (non-negative values summing to one) so two numbers describes all three topics.

To get the coefficients and standard errors we do the following. For each simulation draw from a multivariate normal centered at the ols estimates with the estimated variance-covariance matrix. We take a number of draws (500 by default) for each simulation. We then collect them all together and summarize that full distribution. It is based on the approach described in this paper: https://gking.harvard.edu/files/gking/files/making.pdf

**Comment by bstewart** [comment]
Your model doesn't know anything about the meta variable but your text was generated from a process affected by the meta variable and then the model learned from the text.  Imagine for example that I decide to cluster people (topics) on the basis of their incomes (words).  I don't know anything about the jobs (meta) those people have.  You can however bet the clusters of people (topics) correlate with the jobs (meta).

The summary is just providing a summary over the individual simulations.  You can think about it as integrating over the uncertainty in the thetas.

**Comment by Ledolter** [comment]
Need to think about both ....

I had the impression that you were just simulating the topic probabilities from the given model which is described by just the means (as no meta variables are specified) and the sigma matrix. So I thought this wouldn't involve anything else (certainly not the word frequencies in the documents). Am I correct on that? If I am, then there shouldn't be any relationship to the meta variable .... sorry to be so persistent (or perhaps stupid)

Hannes

Sent from my iPhone

On May 2, 2017, at 5:20 PM, Brandon Stewart <notifications@github.com<mailto:notifications@github.com>> wrote:


Your model doesn't know anything about the meta variable but your text was generated from a process affected by the meta variable and then the model learned from the text. Imagine for example that I decide to cluster people (topics) on the basis of their incomes (words). I don't know anything about the jobs (meta) those people have. You can however bet the clusters of people (topics) correlate with the jobs (meta).

The summary is just providing a summary over the individual simulations. You can think about it as integrating over the uncertainty in the thetas.

**Comment by bstewart** [comment]
Simulation in this context doesn't mean simulating fake data- its part of a numerical estimation procedure.  Does that help?

**Comment by Ledolter** [comment]
Thanks for the feedback. Need to think about it some more. Hannes

I have a PhD student here at Iowa who is planning to look at topics models. Right now she is looking at simulations when we do know the words in the various topics ....

I got into this area when my wife, a legal historian, asked me to some textual analysis of a large corpus of letters. We are getting to the stage when we actually can look at models. So far it has been all work on fixing up the source text (hand-written letters and OCT ... lots of text cleaning). Also have to/from information so chance of network information

Lots to learn!



Sent from my iPhone

On May 2, 2017, at 5:53 PM, Brandon Stewart <notifications@github.com<mailto:notifications@github.com>> wrote:


Simulation in this context doesn't mean simulating fake data- its part of a numerical estimation procedure. Does that help?

**Comment by Ledolter** [comment]
Brandon:

I read the paper by the Harvard group and I understand how you get the standard errors in summary(estimateEffect …). Thanks. I am convinced.

However I am still puzzled about getting significant relationship to the meta variable if my model in estimateEffect does not make use of the meta variable.

results10=stm(ccc$documents,ccc$vocab,K=3)
results10$mu

No meta data is used in the above model. The topic occurrence is characterized by the two means (third mean is implied because of restrictions in logistic model).

I assume that topic probabilities for each of the documents are generated from this one common model (with given results10$mu and results10$sigma).

If I now simulate the topic assignments for the say M=10,000 documents, the simulated results are drawn from the same distribution. If we look at the topic proportions (across all M=10,000 documents) from that simulation, the topic distribution should mimic the probabilities from the model in results10.

Furthermore if we calculate separate topic proportions for each of the levels of the meta variable (which we haven’t communicated to the model in results10), the simulated topic proportions should not differ across the levels of the (withheld) meta variable. And if we carry out a regression analysis, the effects of the meta variable should be insignificant.
prep <- estimateEffect(1:3~factor(ids2),results10,nsims=50)
summary(prep)                ## assesses significance of meta variables
prep$parameters

Where do I go wrong?

Thanks
Hannes

**Comment by bstewart** [comment]
The big difference is that you are fitting a model based on real data.  So let's say I have a thousand documents 500 written by group A and 500 written by group B and each group writes differently. Even if I don't include the groups in my original model specification, it is still the case that group A and B are writing about different things and consequently we will see a difference in the learned topics for A's document and B's documents.  This makes perfect sense because they have written about different things entirely!  

If by contrast you generated a completely random covariate, say by taking draws from a normal distribution, we should not expect to see any relationship.

**Comment by Ledolter** [comment]
Brandon:

Thanks for being so patient. I think I finally figured out my error.

I had the wrong impression that the simulations of the topic probabilities for the ith document were generated from the prior distribution p(theta(i)|mu,sigma) where mu and sigma are the estimates from model results10. I now see that the simulations must be from the posterior distribution p(theta(i)|mu,sigma, DATA on all M documents).
Posterior estimates of the document-specific thetas are given in results10$theta. These estimates can be regressed on the meta variable factor(ids2) and the results are then shown as the first simulation  in the output from estimateEffect(1:3~factor(ids2),results10,nsims=50)$parameters.

Under the global setting you then simulate the prior means by adding to the vector mu realizations from randomly-drawn normal deviates with mean vector zero and variance matrix sigma. And from there you obtain the estimates of the posterior distribution (posterior on all data). And these you regress on the meta variable factor(ids2) – for the second simulation. And so on.

I hope I got this right now.
Thanks
Hannes

**Comment by bstewart** [comment]
I think you've got it right but let me restate a couple of things just to be clear.

1. The matrix in results10$theta are the MAP estimates (posterior mode).
2. The "local" options takes draws from the approximate posterior and calculates the regression on each summarizing over all of them (i.e. integrating over the posterior).
3. The "global" option is an approximation to the process in 2.  We use the posterior mode for each document, but use a 'global' estimate of the posterior covariance that rather than be document specific is shared by all the documents.  The theory here is that knowing all the individual document-level covariance matrices doesn't change the final estimates that much and it is much, much faster.  The covariance matrix isn't quite Sigma but is instead the average of the individual document covariance matrix (which can be recovered fairly quickly from Sigma).

So its the last paragraph of yours that might still not be right?

**Comment by Ledolter** [comment]
Got it! Much thanks  Hannes

**Comment by Ledolter** [comment]
Brandon:

Sorry for the bother. I am getting better, but slowly.

I am using both stm and tm. I know how to get the sparse matrix of frequencies when I am coming from stm. I just use: uuu=convertCorpus(docs, vocab, type = "slam")

But how can I convert this matrix to a term-document matrix that is recognized by tm so that I can work with their tm functions on term-frequency matrices (such as getting frequencies, correlations …)? Is there an easy way? I can’t seem to find anything in the stm and tm documents.

Thanks Hannes

**Comment by bstewart** [comment]
I'd recommend doing the text processing analysis in quanteda or tm and then converting to stm for doing the topic modeling.  For functions that take in sparse matrices and import them into tm you'd have to look at the tm import tools.

**Comment by Ledolter** [comment]
Thanks. Yes, I can always do that. Just thought there was an easy way to go back and forth (as the preprocessing in tm and stm may not always be identical). Hannes

**Comment by Ledolter** [comment]
Brandon

I have asked you questions on several occasions before, and you have helped me out many times. Thank you.

My text mining projects are progressing and I am learning (although slowly). I am using stm as well as tm, and I am struggling with the interpretation of topic models.

But the question I have today is not on the interpretation, but on the technical side on how to go from tm to stm (I do know how to go from stm to tm).

I start with tm, reading in the data (which I have pre-processed before) and creating the corpus. Then I create the document term matrix.

write.csv(datacomb,"C:\\Users\\ledolter\\Desktop\\NewestAnalysisTextMining\\datacomb.csv")           ## create outfile
data <- read.csv("C:\\Users\\ledolter\\Desktop\\NewestAnalysisTextMining\\datacomb.csv",stringsAsFactors=F)
dim(data)
data[1:10,1:5]
## data$text includes the text
## the other entries are the meta data
ids1=data$indc
ids2=data$autr
ids3=data$recr
ids4=data$yearc

corpus <- Corpus(VectorSource(data$text),readerControl = list(reader = readPlain))
## this is how I create the corpus
corpus1 <- tm_map(corpus, stripWhitespace)
corpus2 <- tm_map(corpus1, content_transformer(tolower))
corpus3 <- tm_map(corpus2, removePunctuation)
corpus4 <- tm_map(corpus3, removeNumbers)
corpus5 <- tm_map(corpus4, removeWords, stopwords("english"))

corp.dtm <- DocumentTermMatrix(corpus5,control=list(stemming=FALSE))
dim(corp.dtm)
corpStripped.dtm=removeSparseTerms(corp.dtm,0.98)
## terms that show up in at least 2 percent of documents
dim(corpStripped.dtm)


When I go to the structural topic models in stm, I want to work with the document matrix that has removed sparse terms (I get too many meaningless terms from the topic models on all the terms). Is there a simple way to get from corpstripped.dtm in tm to stm, so that I can fit the structural topic models? (meta variables are in ids1-ids4).

Thanks
Hannes
Johannes Ledolter
University of Iowa

**Comment by bstewart** [comment]
`readCorpus` should handle conversion from tm to stm format.  The option you want is `type=slam` which is the version tm uses under the hood for the dtms

**Comment by Ledolter** [comment]
Thanks, Brandon. I think I figured it out. Hannes
