### ISSUE TITLE
Does this package work only for texts in english?

### ISSUE THREAD

**Issue by jpmarindiaz** [bstewart/stm#6]
Does it include english specific code? Can I simply input spanish text and it would work?

**Comment by bstewart** [comment]
The analysis itself is language agnostic.  The preprocessing (stemming etc.) requires language specific tools.  However the function textProcessor function supports a dozen or so languages including Spanish.

**Comment by tingleyd** [comment]
Yep good we also published a paper in political analysis that addresses
this question .

**Comment by jpmarindiaz** [comment]
Great, thanks!
