### ISSUE TITLE
fitNewDocuments and documents with 1 term

### ISSUE THREAD

**Issue by OO00OO00** [bstewart/stm#60]
Hi Brandon,

Can you confirm whether the following behavior is expected for fitNewDocuments? 

If a hold-out corpus has only 1 term in it, fitNewDocuments will throw the error, "not a matrix", during the optimization step. If I force all documents to have at least 2 terms, I do not receive an error. Is this expected? I don't see it in the documentation, although it's reasonable to expect weird behavior when a document is almost empty.

Thanks!

**Comment by bstewart** [comment]
No this isn't expected!  Sorry about that and thanks for flagging the issue.  R does strange things with simplifying data structures sometimes and it looks like there is an edge case here I missed.  When I have a chance I'll sit down and figure out what is going on.

**Comment by OO00OO00** [comment]
Thanks, Brandon. As a follow-up, the issue appears to be a bit deeper: fitNewDocuments fails when a document has 1 term OR 1 distinct term (with a frequency > 1). I'll see if I can make reproducible code to demonstrate this, but not sure when based on my availability.

HTH

**Comment by bstewart** [comment]
Great- fixed this.  Thanks again for the report.
