### ISSUE TITLE
fitNewDocuments and prevalencePrior = "Average"

### ISSUE THREAD

**Issue by OO00OO00** [bstewart/stm#61]
Hi Brandon,

The following describes a likely bug:

When scoring new documents with fitNewDocuments from a correlated topic model, I receive an error re: mu[,i]. Although I don't have the full error message at the moment, the error appears related to lines 181 and 282 of the fitNewDocuments code block [here](https://rdrr.io/cran/stm/src/R/fitNewDocuments.R). Namely, when:

- prevtype == "Average",

- gamma  is not null, and

- the topic model is a CTM

mu is a vector (line 181). However, on line 282, mu is referenced as a matrix. The function appears to work properly by changing the source code to ensure mu is a matrix for the case described above, e.g.

Please let me know if my observations are not reasonable. Thanks!

**Comment by bstewart** [comment]
Ah- this makes perfect sense.  Thank you!  I'll address this case in the next update and close this out when I have code up on github.  Thank you!

**Comment by iamishalkin** [comment]
Could you be so kind to write step-by-step what should I do the evade the error?
And is this error similar to one I get in  [here](https://github.com/bstewart/stm/issues/8) (the last post)?

**Comment by bstewart** [comment]
I'm having some trouble building due to package dependency issues but the version up now should resolve this problem.
