### ISSUE TITLE
DMR topic model?

### ISSUE THREAD

**Issue by lieove** [bstewart/stm#7]
it's wonderful. And I try to use DMR topic model, but i find there is something wrong with the parameter init.type of manyTopics function. 
like this:
Error in match.arg(init.type) : 
'arg' should be one of "LDA", "Random", "Spectral"
I install the latest version 1.0.12.
Why? Hope you can help me. Thanks!

**Comment by bstewart** [comment]
I'm not really sure.  I'll take a look.

In the interim- I'd recommend using the searchK() function instead.  Its a bit more robust and will probably do what you need it to do.  Also take a look at the new vignette here: https://github.com/bstewart/stm/blob/master/inst/doc/stmVignette.pdf?raw=true

**Comment by bstewart** [comment]
Also could you post a reproducible example?  It would be quite helpful in identifying the problem.  You can use the help file for manyTopics to construct one with the data in the package.

**Comment by lieove** [comment]
As the help file said, the init.type of selectModel and manyTopics must be either Latent Dirichlet Allocation (LDA), Dirichlet Multinomial Regression Topic Model (DMR), a random initialization\
or a previous STM object. I follow the example, and i want to use DMR . so i add the parameter init.type='DMR' in the manyTopics and selectModel . Both of them can't work. And i found init.type  shoule be one of "LDA", "Random", "Spectral", but not 'DMR'.
The example is as follows.
###########
library(stm)
temp<-textProcessor(documents=gadarian$open.ended.response,metadata=gadarian)
meta<-temp$meta
vocab<-temp$vocab
docs<-temp$documents
out <- prepDocuments(docs, vocab, meta)
docs<-out$documents
vocab<-out$vocab
meta <-out$meta
set.seed(02138)
storage<-manyTopics(docs,vocab,K=3:4, prevalence=~treatment + s(pid_rep),data=meta, runs=10, init.type='DMR')
##############
And when change init.type='LDA', it works.
So i'm confuse about it and it not match as the help file.
