### ISSUE TITLE
Error in validObject(r) :   invalid class “dgTMatrix” object: lengths of slots i and j must match

### ISSUE THREAD

**Issue by Ninoninoninonino** [bstewart/stm#70]
When running a batch script I get the error code

`stm v1.2.1 (2017-03-06) successfully loaded. See ?stm for help.
Error in validObject(r) :
  invalid class “dgTMatrix” object: lengths of slots i and j must match
Calls: stm ... stm.control -> opt.beta -> mnreg -> sparseMatrix -> validObject
Execution halted
`

Batch script:

`
library(quanteda)
library(stm)
library(pryr)

setwd("/home/XXX/Scratch/R_output/tmpdir/Corpora2Analyse")
load("presDfmSTM")
load("PostProcessMeta") # called meta

mem_used()

mem_change(wood_cement_content <- stm(presDfmSTM$documents, presDfmSTM$vocab, K=0, prevalence = ~ Interest + Region, content= ~ Interest, max.em.its = 1, data = meta, init.type = "Spectra$

t <- system.time(wood_cement_content <- stm(presDfmSTM$documents, presDfmSTM$vocab, K=0, prevalence = ~ Interest + Region, content= ~ Interest, max.em.its = 1, data = meta, init.type = "S$

iterations <- 3

repeat {
  wood_cement_content <- stm(presDfmSTM$documents, presDfmSTM$vocab, K=0, prevalence = ~ Interest + Region, content= ~ Interest,
                             max.em.its = iterations, data = meta, model = wood_cement_content, init.type = "Spectral")

  iterations <- iterations + 1

  if(stmFitted$convergence$converged == TRUE){
    break
  }
  save(wood_cement_content, file="/home/XXX/Scratch/R_output/tmpdir/Corpora2Analyse/wood_cement_content_not_converged")
  print(iterations)
}
save(wood_cement_content, file="/home/XXX/Scratch/R_output/tmpdir/Corpora2Analyse/wood_cement_content_converged")

`

Output from batch script:

`> 
> library(quanteda)
> library(stm)
> library(pryr)
>
>
> setwd("/home/XXX/Scratch/R_output/tmpdir/Corpora2Analyse")
> load("presDfmSTM")
> load("PostProcessMeta") # called meta
>
>
> mem_used()
222 MB
>
>
> mem_change(wood_cement_content <- stm(presDfmSTM$documents, presDfmSTM$vocab, K=0, prevalence = ~ Interest + Region, content= ~ Interest, max.em.its = 1, data = meta, init.type = "Spect$
Note: no visible binding for global variable 'Dimnames'
Note: no visible binding for global variable 'Dimnames'
Note: no visible binding for global variable 'Dimnames'
Beginning Initialization.
         Calculating the gram matrix...
Note: no visible binding for global variable 'Dimnames'
Note: no visible binding for global variable 'Dimnames'
Note: no visible binding for global variable 'Dimnames'

 Finding anchor words...

         Recovering initialization...
        ..............................................................................................
Initialization complete.
....................................................................................................
Completed E-Step (601 seconds).
....................................................................................................
Completed M-Step (613 seconds).
Model Terminated Before Convergence Reached
266 MB
>
>
> t <- system.time(wood_cement_content <- stm(presDfmSTM$documents, presDfmSTM$vocab, K=0, prevalence = ~ Interest + Region, content= ~ Interest, max.em.its = 1, data = meta, init.type = $
Beginning Initialization.
         Calculating the gram matrix...
         Finding anchor words...

         Recovering initialization...
        ..............................................................................................
Initialization complete.
....................................................................................................
Completed E-Step (638 seconds).
....................................................................................................
Completed M-Step (906 seconds).
Model Terminated Before Convergence Reached

>
>
>
> iterations <- 3
>
>
> repeat {
+   wood_cement_content <- stm(presDfmSTM$documents, presDfmSTM$vocab, K=0, prevalence = ~ Interest + Region, content= ~ Interest,
+                              max.em.its = iterations, data = meta, model = wood_cement_content, init.type = "Spectral")
+   iterations <- iterations + 1
+   if(stmFitted$convergence$converged == TRUE){
+     break
+   }
+   save(wood_cement_content, file="/home/XXX/Scratch/R_output/tmpdir/Corpora2Analyse/wood_cement_content_not_converged")
+   print(iterations)
+ }
Note: no visible binding for global variable 'stmFitted'
Restarting Model...
....................................................................................................
Completed E-Step (477 seconds).

`
SessionInfo:

`> sessioninfo()
Error: could not find function "sessioninfo"
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.2 (Maipo)

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
`

Files: 

* https://transfer.sh/ZW9mn/PostProcessMeta
* https://transfer.sh/3uEyW/presDfmSTM

**Comment by bstewart** [comment]
My understanding is that this is a bug in the Matrix package.  Try adding library(methods) at the top of the script.  This worked for us here- but let me know if it fails to resolve your problem.

**Comment by bstewart** [comment]
I'm assuming this was taken care of but please reopen if this didn't resolve the issue.
