### ISSUE TITLE
problems with Rtsne

### ISSUE THREAD

**Issue by noenovels** [bstewart/stm#71]
Hi! 
I have a problem when running stm(), with k=0. 
I'm working with a trimmed dfm (4613 x 6048 sparse Matrix of class "dfmSparse", with 396486 entries).

The following error shows:
Error in tsneAnchor(Q) : an unknown error has occured in Rtsne

The weird thing is that I have run the command different times and I never had this problem before (it has happened in the last week only).
Do you have any suggestion on what the problem may be?

Thanks, 
Noemi

**Comment by bstewart** [comment]
Regular stm() works but not k=0?  Assuming that's true could you perhaps send me a short replication file so I can reproduce the problem?

**Comment by noenovels** [comment]
Yes, it works with set k, not with k=0.
I attach a file here.
[rep_file.txt](https://github.com/bstewart/stm/files/987389/rep_file.txt)

**Comment by bstewart** [comment]
Can you send me the file as well so I can reproduce it?  Feel free to email me a link if you would prefer.  I'll delete when I'm done, I just need to be able to actually reproduce the error on my machine.

**Comment by noenovels** [comment]
Sure, I'll send you an email.
Thank you again,
Noemi

**Comment by bstewart** [comment]
Fascinating.  Thanks for sharing this.  So what is happening here is that while there are no duplicates in the original data, there are duplicates in the first 50 principal components.  I don't exactly know why that's happening, but its easy enough to fix by moving the pca component outside the RTSNE function.  It might take me a week or two to get to it, but I will.

**Comment by spnichol** [comment]
Hey Brandon,

I don't know if it helps, but this is also happening to me. I've tried it multiple times with different corpus (but always K=0) with no success. 

PS. Enjoyed your talk in Spirling's class a few weeks ago.

**Comment by bstewart** [comment]
Thanks!  I find this to be so interesting.  I'm sure I can fix it- i just need a bit of spare time to do so.  Sorry for the inconvenience.

And thanks for the complements on the talk!

**Comment by spnichol** [comment]
No worries. And it is really strange, considering it was working fine a few weeks ago. Fixed K for the time being!

**Comment by methodds** [comment]
I just wanted to confirm that I experience the same problem when setting `K = 0`.

**Comment by adeldaoud** [comment]
I would like to report the same problem here as well.  

```
> stmFit <- stm(out$documents, out$vocab, K = 0, prevalence =~ s(Year) , 
+               max.em.its = 150, data = out$meta, init.type = "Spectral", seed = 300, verbose = T)

> Beginning Initialization.
> 	 Calculating the gram matrix...
> 	 Finding anchor words...
>  	
> Error in tsneAnchor(Q) : an unknown error has occured in Rtsne
```

**Comment by bstewart** [comment]
Okay- I made some changes which should fix this in the development branch.  I'll do some testing and then fold into the master.  Thanks for the patience everyone.  Plus side- it should both work AND be faster.
