### ISSUE TITLE
make.heldout can return non-integer document objects

### ISSUE THREAD

**Issue by LouHb** [bstewart/stm#74]
Hi,
I've recently had a problem running the `selectModel` function with the `make.heldout` output.

Here's the code I ran:
`heldout <- make.heldout(dtm$documents, dtm$vocab, N = floor(0.1 * length(MAdtm$documents)), proportion = 0.5, seed = 1234)`

(no error so far)

`STM_SelectHeldout <- selectModel(heldout$documents, heldout$vocab, K=30, prevalence=~ KeywordID + s(Year), max.em.its=5, data=MAmeta, runs=20)`

And here's the error (unfortunately, there are parts in german)
`Fehler in structure(.Call("collapsedGibbsSampler", documents, as.integer(K),  : document must be a matrix with 2 rows of type Integer.`

I don't unterstand, what's the problem in this case. The `heldout$documents` object has the same structure (to me) like the `dtm$documents` (in this case dtm is a corpus, by the way, not a document-term-matrix - might be confusing). 

Thanks!
Louise

**Comment by bstewart** [comment]
Louise,

Can you send me a reproducible example so I can recreate the error over here?   You might double check the N argument since you are referencing something different entirely- is it returning something reasonable?  

As an aside- I would in general recommend the spectral initialization over selectModel anyway. 

Brandon

**Comment by LouHb** [comment]
Sure, I'll send you an e-mail with some data.
Thanks for the spectral initialization advice!

Louise

**Comment by bstewart** [comment]
Thank you! It looks like something in the heldout is causing the documents to be recast as non-integer values.  You can fix it with the following code:
`heldout$documents <- lapply(heldout$documents, function(x) matrix(as.integer(x), nrow(x), ncol(x)))
`
I will fix this in the next release.  Thanks for bringing it to my attention.

**Comment by bstewart** [comment]
I also renamed the issue to more clearly reflect the underlying problem.

**Comment by LouHb** [comment]
Great! Thanks for your immediate response and help!
