### ISSUE TITLE
Example cases for reasons why y

### ISSUE THREAD

**Issue by Ninoninoninonino** [bstewart/stm#78]
I often get the error that the covariate matrix is singular. It would be great to have some more text analysis specific examples of when we can expect this to occur. On this basis we could work out some automatic tests, which could be performed prior to the estimation of the STM.

**Comment by bstewart** [comment]
So this doesn't require anything special.  It is a consequence of the covariate matrix only so you can generate a random outcome and then run a regression using `lm` and see if its singular.
