### ISSUE TITLE
Automated differentiated correlations?

### ISSUE THREAD

**Issue by Ninoninoninonino** [bstewart/stm#79]
Is there a built-in way to generate correlations differentiated according to different covariates as in the article "A Model of Text for Experimentation in the Social Sciences" (http://scholar.princeton.edu/sites/default/files/bstewart/files/a_model_of_text_for_experimentation_in_the_social_sciences.pdf) ? Or would one need to run the Huge package separately?

**Comment by bstewart** [comment]
There is no built in function but its pretty straightforward- you just subset and then create the graph in whatever way you wanted to (using Huge or just thresholding the correlation matrix)

**Comment by Ninoninoninonino** [comment]
Thanks, I guess I need to subset the STM model object.. 

I'm fine with subsetting dataframes.. According to which schema can I subset STM objects? 

Should I go via data.table?

**Comment by bstewart** [comment]
Whatever you are most comfortable with.  The object you want is 
`mod$theta`
