### ISSUE TITLE
textProcessor data frame coercion

### ISSUE THREAD

**Issue by bstewart** [bstewart/stm#80]
data.table() and I expect tibbles have some edge case problems with textProcessor.  Need to force a coercion to ensure consistent behavior.

**Comment by methodds** [comment]
Is there a reason why you don't use quanteda as the backend for text processing?

**Comment by bstewart** [comment]
The simple reason is that it didn't exist when we first wrote the function.  More recently because the API is in the process of changing and I didn't want to rewrite it twice.  We should move this over though at some point.

It also breaks backwards compatability which I'm always reluctant to do because it makes it harder for people to replicate prior results.

**Comment by bstewart** [comment]
Moved the request here to #93.  Going to close this out.
