### ISSUE TITLE
Use LDA instead of CTM or STM?

### ISSUE THREAD

**Issue by OO00OO00** [bstewart/stm#82]
Is it possible to use the stm package with LDA alone, as opposed to CTM or STM? i.e., build a topic model that doesn't model topic correlations or use other design matrices? I know LDA can be used for initialization and I know there are other packages for this. However, I don't see how stm could produce a topic model solely built via collapsed Gibbs. I suspect it's out of scope for this package, but wanted to confirm.

Thanks!

**Comment by bstewart** [comment]
Correct.  Right now its out of scope.  It is something I'd like to add at some point- but I don't know when I'll have the time!  I could add a way to get the initialization out, but honestly I think I'd want to be sure to do it right (optimize the hyperparameters, average over the draws etc.)

**Comment by OO00OO00** [comment]
Yep, agreed on your approach. Thanks for the fast response!
