### ISSUE TITLE
summary.estimateEffect doesn't work in all cases

### ISSUE THREAD

**Issue by crew102** [bstewart/stm#85]
Greetings -

Currently, when `summary.estimateEffect` loops over the `object$parameters` to pull out the relevant topic data, it is subsetting the `parameters` list incorrectly. Specifically, it is subsetting using topic numbers, when it should be using an integer index [here](https://github.com/bstewart/stm/blob/127e6ecf136c88570b0c66f73560e684ebb38eb9/R/estimateEffect.R#L293). This works most of the time by coincidence, due to the fact that that the topic numbers are usually valid integer indexes for the list. For example, these calls all work:

```r
library(stm)
data("gadarianFit")

prep <- estimateEffect(c(1) ~ treatment, gadarianFit, gadarian)
summary(prep) # works

prep <- estimateEffect(1:3 ~ treatment, gadarianFit, gadarian)
summary(prep) # works
```

...But these don't:

```r
prep <- estimateEffect(c(2) ~ treatment, gadarianFit, gadarian)
summary(prep) # errors
#> Error in object$parameters[[topics[i]]]: subscript out of bounds

prep <- estimateEffect(2:3 ~ treatment, gadarianFit, gadarian)
summary(prep) # errors
#> Error in object$parameters[[topics[i]]]: subscript out of bounds
```

This can easily be fixed (PR on its way) by changing `lapply(object$parameters[[topics[i]]], function(x) rmvnorm(nsim, x$est, x$vcov))` to `lapply(object$parameters[[i]], function(x) rmvnorm(nsim, x$est, x$vcov))`.

**Comment by bstewart** [comment]
Wow this is a great and important catch.  Thank you!  I'm trying to figure out what is causing the crash in the pull request...
