### ISSUE TITLE
memory use for spectral initialization

### ISSUE THREAD

**Issue by methodds** [bstewart/stm#9]
Hi,

whenever I try to use spectral  initialization (either for `searchK` or `stm` fit) all my remaining memory space (~13GB) is instantly consumed and R crashes with the error:

```
Error: cannot allocate vector of size 1.7 Gb
```

I tried this on Windows 10 and Linux Mint 17.  My corpus has 20133 documents, 21532 terms and 402629 tokens.

Despite this, while `LDA` initialization works completely fine for model fitting, it crashes on the `searchK`function:

```
storage<-searchK(documents, vocab, K=c(40,60), init.type = 'LDA',
                     prevalence =~ CIO2,  data=meta)

Beginning Initialization.
Error in structure(.Call("collapsedGibbsSampler", documents, as.integer(K),  : 
  document must be a matrix with 2 rows of type Integer.
```

CIO2 is a binary variable from the meta object. I'm using stm version 1.10. Do you have an idea what is going wrong here?

**Comment by bstewart** [comment]
We discussed this a bit on email but I wanted to leave a response here summarizing the main points for anyone else who might run across this:
1) As it currently stands the spectral initialization has to allocate and operate on a matrix that is # of terms by # of terms.  This makes it very sensitive to the vocab size and will work much better if you cut down the vocab with prepDocuments.
2) I'm not entirely sure what's happening with the LDA for searchK but I wouldn't recommend it anyway (use spectral instead the variance here is too high for each run).  I'll look into it though.
3) always make sure you are using the latest version.  this is a few releases back.

**Comment by methodds** [comment]
Is there a formula to roughly estimate the amount of RAM needed for fitting a model with spectral initialization? I probably need to rent hardware for a large model and have no idea how I could calculate RAM requirements.

**Comment by bstewart** [comment]
No formula per se- but here is something that might help.

The largest constraint is a V^2 dimensional matrix where V is the length of the vocab.  So probably something like V^2(8/1e6) MB  is the approximate size of your largest object.  This object will dwarf all the others in size so if you have some breathing room on top of that you should be fine.

**Comment by bstewart** [comment]
I've now updated this so it never uses more than 10,000 words (modifiable limit via control).  This effectively addresses this issue.

**Comment by Ninoninoninonino** [comment]
Where does the size of the corpus come into the formula 

> V^2(8/1e6) MB

?

**Comment by bstewart** [comment]
It doesn't.  The initialization operates on an object independent of the number of documents.  

You also need two copies of a matrix of size N by K where N is the number of documents but for K small this isn't a huge deal until N gets really large.
