### ISSUE TITLE
fitnewDocuments

### ISSUE THREAD

**Issue by danjgibbons** [bstewart/stm#96]
Firstly, this is an amazing package with really great functionality so thank you for contributing this to the community.

Secondly, I'm having a bit of an issue understanding/using fitnewDocuments, which I can't quite tell is an error or my own daftness. I would like to find the topic prevalence for _all_ the documents in my original dataset, as I want to use these prevalence values for prediction.

As an example if I use the gadarian data, fitNewDocuments(model=mod.out, documents=out$documents[1:16], newData=out$meta[1:16,], origData=out$meta, prevalence=~treatment + s(pid_rep), prevalencePrior="Covariate") produces the error Error in fn(par, ...) : Not a matrix. but using 1:15 does not.

Similarly, for other data I tend to find that fitnewDocuments does not like if the new data is a large fraction of the original data. I'm therefore wondering if:
1) this can be fixed by me easily or if its inbuilt;
2) if it is therefore better to cross-validate the STM and then predict rather than trying an STM on the whole dataset first?

**Comment by bstewart** [comment]
Thanks!

So first- you don't actually need to use fitNewDocuments.  The topic proportions are just calculated as part of the regular model fit and you can find them all in `mod.out$theta`.  

However, I don't know why you are having a problem with the other thing.  Could you send me a replicable example of the error so I can run it down?

**Comment by JohnNay** [comment]
Can you use new data for `fitNewDocuments` other than the data processed in the processing for the model fitting?

```
temp<-textProcessor(documents=gadarian$open.ended.response,metadata=gadarian)
out <- prepDocuments(temp$documents, temp$vocab, temp$meta)
set.seed(02138)
#Maximum EM its is set low to make this run fast, run models to convergence!
mod.out <- stm(out$documents, out$vocab, 3, prevalence=~treatment + s(pid_rep), 
              data=out$meta, max.em.its=5)

# can you run this one new data here?
temp2<-textProcessor(documents=gadarian2$open.ended.response,metadata=gadarian2)
out2 <- prepDocuments(temp2$documents, temp2$vocab, temp2$meta)

fitNewDocuments(model=mod.out, documents=out2$documents, newData=out2$meta,
               origData=out2$meta, prevalence=~treatment + s(pid_rep),
               prevalencePrior="Covariate")
```

**Comment by bstewart** [comment]
For the release in master branch of the github, see the function `alignCorpus()`
